# Generated by Django 6.0.1 on 2026-01-06 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Ano de término da temporada (Ex: 2024 para 2023/24)')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('played', models.IntegerField()),
                ('won', models.IntegerField()),
                ('drawn', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('goals_for', models.IntegerField()),
                ('goals_against', models.IntegerField()),
                ('points', models.IntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='matches.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='matches.team')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='matches.season')),
            ],
            options={
                'ordering': ['season', 'league', 'position'],
                'unique_together': {('league', 'season', 'team')},
            },
        ),
    ]
