# Generated by Django 6.0.1 on 2026-01-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_alter_match_options_match_ht_away_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='elapsed_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
