# Generated by Django 6.0.1 on 2026-01-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_match_h2h_data_match_predictions_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='api_id',
            field=models.CharField(blank=True, help_text='ID da Fixture na API', max_length=50, null=True, unique=True),
        ),
    ]
