# Generated by Django 6.0.1 on 2026-01-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_match_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='api_id',
            field=models.CharField(blank=True, help_text='ID do Time na API', max_length=50, null=True, unique=True),
        ),
    ]
