# Generated by Django 6.0.1 on 2026-01-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_match_away_corners_match_away_fouls_match_away_red_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='api_id',
            field=models.CharField(blank=True, help_text='ID da Fixture na API', max_length=255, null=True, unique=True),
        ),
    ]
