# Generated by Django 6.0.1 on 2026-02-18 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamGoalTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scored_0_15', models.IntegerField(default=0)),
                ('scored_16_30', models.IntegerField(default=0)),
                ('scored_31_45', models.IntegerField(default=0)),
                ('scored_46_60', models.IntegerField(default=0)),
                ('scored_61_75', models.IntegerField(default=0)),
                ('scored_76_90', models.IntegerField(default=0)),
                ('conceded_0_15', models.IntegerField(default=0)),
                ('conceded_16_30', models.IntegerField(default=0)),
                ('conceded_31_45', models.IntegerField(default=0)),
                ('conceded_46_60', models.IntegerField(default=0)),
                ('conceded_61_75', models.IntegerField(default=0)),
                ('conceded_76_90', models.IntegerField(default=0)),
                ('scored_1st_half', models.IntegerField(default=0)),
                ('scored_2nd_half', models.IntegerField(default=0)),
                ('conceded_1st_half', models.IntegerField(default=0)),
                ('conceded_2nd_half', models.IntegerField(default=0)),
                ('avg_min_scored', models.IntegerField(blank=True, default=0, null=True)),
                ('avg_min_conceded', models.IntegerField(blank=True, default=0, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_timings', to='matches.league')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_timings', to='matches.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_timings', to='matches.team')),
            ],
            options={
                'ordering': ['league', 'season', 'team'],
                'unique_together': {('league', 'season', 'team')},
            },
        ),
    ]
