# Generated by Django 6.0.1 on 2026-02-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_teamgoaltiming'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(help_text='Nome da API/Chave (ex: The Odds API - Live)', max_length=100)),
                ('credits_used', models.IntegerField(default=0, help_text='Créditos usados na última requisição')),
                ('credits_remaining', models.IntegerField(default=0, help_text='Créditos restantes retornados no header')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
