# Generated by Django 6.0.1 on 2026-02-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_apiusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_team_win_odds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='draw_odds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_win_odds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
