# Generated by Django 6.0.1 on 2026-03-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0013_match_away_team_win_odds_match_draw_odds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='division',
            field=models.IntegerField(default=1, help_text='Nível da liga: 1=Primeira Divisão, 2=Segunda, etc.'),
        ),
        migrations.AddField(
            model_name='league',
            name='soccerstats_slug',
            field=models.CharField(blank=True, help_text="Slug único no SoccerStats.com (ex: 'england', 'denmark'). Usado para evitar mistura entre divisões.", max_length=100, null=True, unique=True),
        ),
    ]
