# Generated by Django 5.0.1 on 2026-03-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0015_merge_20260301_2301'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('name', 'league'), name='unique_team_name_per_league'),
        ),
    ]
