# Generated by Django 5.0.1 on 2026-03-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0016_team_unique_team_name_per_league'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('home_team', 'away_team', 'date'), name='unique_match_fixture'),
        ),
    ]
