# Generated by Django 5.0.1 on 2026-05-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0017_match_unique_match_fixture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaguestanding',
            options={'ordering': ['season', 'league', 'group_name', 'position']},
        ),
        migrations.AlterUniqueTogether(
            name='leaguestanding',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='group_name',
            field=models.CharField(default='Regular Season', help_text='Ex: Regular Season, Championship Round', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='leaguestanding',
            unique_together={('league', 'season', 'team', 'group_name')},
        ),
    ]
