# Generated by Django 5.0.1 on 2026-05-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0018_alter_leaguestanding_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguestanding',
            name='points_curr_season',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='points_per_game',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='points_prev_prev_season',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='points_prev_season',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
