# Generated by Django 6.0.1 on 2026-05-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0019_leaguestanding_points_curr_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='round_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
