# Generated by Django 6.0.1 on 2026-05-20 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0020_alter_match_round_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título do bilhete (ex: Dupla de Ouro HT)', max_length=200)),
                ('ticket_type', models.CharField(choices=[('Double', 'Dupla'), ('Treble', 'Tripla')], max_length=20)),
                ('average_probability', models.IntegerField(default=0, help_text='Probabilidade média de acerto (%)')),
                ('status', models.CharField(choices=[('Pending', 'Pendente'), ('Green', 'Green ✅'), ('Red', 'Red ❌'), ('Void', 'Anulada')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_target', models.DateField(blank=True, help_text='Data alvo dos jogos deste bilhete', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BetTicketSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_market', models.CharField(help_text='Mercado escolhido (ex: over_15, ht_goal, home_win)', max_length=100)),
                ('prediction_label', models.CharField(help_text='Rótulo amigável (ex: Mais de 1.5 Gols FT)', max_length=100)),
                ('probability', models.IntegerField(default=0, help_text='Probabilidade específica deste jogo')),
                ('status', models.CharField(choices=[('Pending', 'Pendente'), ('Green', 'Green ✅'), ('Red', 'Red ❌'), ('Void', 'Anulada')], default='Pending', max_length=20)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_selections', to='matches.match')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='matches.betticket')),
            ],
        ),
    ]
