# Generated by Django 5.0.1 on 2026-05-27 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0021_betticket_betticketselection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannerTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(help_text='Market identifier (e.g., HT_GOAL, OVER_15, BTTS, HOME_WIN)', max_length=50)),
                ('probability', models.FloatField(default=0.0)),
                ('prediction_text', models.CharField(help_text="User-friendly text (e.g., 'Gol no 1º Tempo')", max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('GREEN', 'Green ✅'), ('RED', 'Red ❌')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanner_tips', to='matches.match')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('match', 'market')},
            },
        ),
    ]
