# Generated by Django 5.0.1 on 2026-05-28 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0022_scannertip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betticket',
            name='ticket_type',
            field=models.CharField(choices=[('Double', 'Dupla'), ('Treble', 'Tripla'), ('Multiple_4_5', 'Múltipla (4-5 Jogos)'), ('Super_6_8', 'Super Múltipla (6-8 Jogos)')], max_length=20),
        ),
        migrations.CreateModel(
            name='MatchMarketOdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmaker', models.CharField(help_text='Nome da casa (ex: bet365, Betfair)', max_length=100)),
                ('market', models.CharField(choices=[('h2h', '1X2 (Moneyline)'), ('totals', 'Over/Under Gols'), ('correct_score', 'Placar Correto')], max_length=30)),
                ('outcome_name', models.CharField(help_text='Ex: Home, Draw, Away, Over, Under, 1-1, 2-0', max_length=50)),
                ('outcome_point', models.FloatField(blank=True, help_text='Linha (ex: 1.5, 2.5 para O/U)', null=True)),
                ('price', models.FloatField(help_text='Odd decimal')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_odds', to='matches.match')),
            ],
            options={
                'ordering': ['match', 'market', 'bookmaker'],
                'indexes': [models.Index(fields=['match', 'market'], name='matches_mat_match_i_bf2234_idx'), models.Index(fields=['bookmaker'], name='matches_mat_bookmak_5b227b_idx')],
                'unique_together': {('match', 'bookmaker', 'market', 'outcome_name', 'outcome_point')},
            },
        ),
    ]
