# Generated by Django 5.0.1 on 2026-05-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0023_alter_betticket_ticket_type_matchmarketodd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betticket',
            name='ticket_type',
            field=models.CharField(choices=[('Double', 'Dupla'), ('Treble', 'Tripla'), ('Multiple_4_5', 'Múltipla (4-5 Jogos)'), ('Super_6_8', 'Super Múltipla (6-8 Jogos)'), ('Hedge_Favorito', 'Hedge ao Favorito')], max_length=20),
        ),
        migrations.DeleteModel(
            name='MatchMarketOdd',
        ),
    ]
