# Generated by Django 5.0.1 on 2026-05-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0025_cleanup_empty_leagues'),
    ]

    operations = [
        migrations.AddField(
            model_name='betticketselection',
            name='odds_val',
            field=models.FloatField(blank=True, help_text='Odd gravada no momento da geracao', null=True),
        ),
        migrations.AlterField(
            model_name='betticket',
            name='ticket_type',
            field=models.CharField(choices=[('Double', 'Dupla'), ('Treble', 'Tripla'), ('Multiple_4_5', 'Múltipla (4-5 Jogos)'), ('Super_6_8', 'Super Múltipla (6-8 Jogos)'), ('Hedge_Favorito', 'Hedge ao Favorito'), ('Trixie', 'Trixie')], max_length=20),
        ),
    ]
