# Generated by Django 5.0.1 on 2026-05-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0026_betticketselection_odds_val_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='betticket',
            name='strategy',
            field=models.CharField(blank=True, help_text='Nome da estratégia (ex: TRIXIE_DC_GOALS)', max_length=50, null=True),
        ),
    ]
