# Generated by Django 5.0.1 on 2026-06-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0027_betticket_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannertip',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('GREEN', 'Green ✅'), ('RED', 'Red ❌'), ('VOID', 'Anulada ➖')], default='PENDING', max_length=20),
        ),
    ]
