# Generated by Django 5.0.1 on 2026-06-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0028_alter_scannertip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='btts_no_odds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='btts_yes_odds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='over_15_odds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='over_25_odds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='over_35_odds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='under_25_odds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='under_35_odds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='under_45_odds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
