# Generated by Django 5.0.1 on 2026-06-09 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0030_match_clean_sheet_away_odds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveMatchSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('minute', models.IntegerField(help_text='Minuto do jogo no momento da coleta')),
                ('home_shots_on_target', models.IntegerField(default=0)),
                ('away_shots_on_target', models.IntegerField(default=0)),
                ('home_shots_off_target', models.IntegerField(default=0)),
                ('away_shots_off_target', models.IntegerField(default=0)),
                ('home_corners', models.IntegerField(default=0)),
                ('away_corners', models.IntegerField(default=0)),
                ('home_dangerous_attacks', models.IntegerField(default=0)),
                ('away_dangerous_attacks', models.IntegerField(default=0)),
                ('home_possession', models.IntegerField(default=50)),
                ('away_possession', models.IntegerField(default=50)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_snapshots', to='matches.match')),
            ],
            options={
                'verbose_name': 'Live Match Snapshot',
                'verbose_name_plural': 'Live Match Snapshots',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['match', '-timestamp'], name='matches_liv_match_i_65f4a8_idx')],
            },
        ),
    ]
