# Generated by Django 5.0.1 on 2026-06-11 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0031_livematchsnapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livematchsnapshot',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveIndex(
            model_name='livematchsnapshot',
            name='matches_liv_match_i_65f4a8_idx',
        ),
        migrations.AlterField(
            model_name='livematchsnapshot',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='matches.match'),
        ),
        migrations.AlterField(
            model_name='livematchsnapshot',
            name='minute',
            field=models.IntegerField(default=0),
        ),
    ]
