# Generated by Django 5.0.1 on 2026-06-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0033_add_live_radar_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='api_id',
            field=models.CharField(blank=True, help_text='ID da Liga na API', max_length=50, null=True, unique=True),
        ),
    ]
