# Generated by Django 5.0.1 on 2026-06-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0034_league_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='fd_id',
            field=models.CharField(blank=True, help_text='ID da Liga na Football-Data', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='match',
            name='fd_id',
            field=models.CharField(blank=True, help_text='ID da Fixture na Football-Data', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='fd_id',
            field=models.CharField(blank=True, help_text='ID do Time na Football-Data', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(db_index=True, default='Scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='scannertip',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('GREEN', 'Green ✅'), ('RED', 'Red ❌'), ('VOID', 'Anulada ➖')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
