# Generated by Django 5.0.1 on 2026-06-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0035_alter_match_date_alter_match_status_and_more'),
        ('matches', '0035_league_fd_id_match_fd_id_team_fd_id_alter_match_date_and_more'),
    ]

    operations = [
    ]
