# Generated by Django 5.0.1 on 2026-08-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0035_league_fd_id_match_fd_id_team_fd_id_alter_match_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nome em português ou padronizado, igual ao campo 'country' da Liga", max_length=100, unique=True)),
                ('intro_en', models.TextField(blank=True, default='')),
                ('intro_pt', models.TextField(blank=True, default='')),
                ('intro_es', models.TextField(blank=True, default='')),
                ('intro_de', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='intro_de',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='league',
            name='intro_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='league',
            name='intro_es',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='league',
            name='intro_pt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
