# Generated by Django 5.0.1 on 2026-08-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0036_country_league_intro_de_league_intro_en_and_more'),
        ('matches', '0036_merge_20260616_1242'),
    ]

    operations = [
    ]
