# Generated by Django 5.0.1 on 2026-08-02 17:01

import json
import os
from django.db import migrations
from django.conf import settings
from django.utils.text import slugify

def load_seo_texts(apps, schema_editor):
    League = apps.get_model('matches', 'League')
    Country = apps.get_model('matches', 'Country')
    
    json_path = os.path.join(settings.BASE_DIR, 'conteudo-lote1.json')
    if not os.path.exists(json_path):
        print(f"\n[!] Arquivo JSON não encontrado: {json_path}")
        return

    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    missing = []
    updated_leagues = 0
    updated_countries = 0

    all_leagues = list(League.objects.all())
    
    for slug_key, texts in data.items():
        try:
            c_slug, l_slug = slug_key.split('/')
        except ValueError:
            missing.append(slug_key)
            continue
            
        found_league = None
        for league in all_leagues:
            db_c_slug = slugify(league.country)
            if league.country.lower() == 'united states':
                db_c_slug = 'usa'
                
            db_l_slug = slugify(league.name)
            
            if db_c_slug == c_slug and db_l_slug == l_slug:
                found_league = league
                break
        
        if found_league:
            found_league.intro_en = texts.get('en', '')
            found_league.intro_pt = texts.get('pt', '')
            found_league.intro_es = texts.get('es', '')
            found_league.intro_de = texts.get('de', '')
            found_league.save()
            updated_leagues += 1
            
            country_obj, _ = Country.objects.get_or_create(name=found_league.country)
            country_obj.intro_en = texts.get('en', '')
            country_obj.intro_pt = texts.get('pt', '')
            country_obj.intro_es = texts.get('es', '')
            country_obj.intro_de = texts.get('de', '')
            country_obj.save()
            updated_countries += 1
        else:
            missing.append(slug_key)
            
    print(f"\n[SEO] Ligas atualizadas: {updated_leagues}")
    print(f"[SEO] Países atualizados: {updated_countries}")
    if missing:
        print(f"[!] Ligas NÃO ENCONTRADAS no banco: {missing}")

class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0036_country_league_intro_de_league_intro_en_and_more'),
    ]

    operations = [
        migrations.RunPython(load_seo_texts, reverse_code=migrations.RunPython.noop),
    ]
