# Generated by Django 5.0.1 on 2026-08-02 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0037_merge_20260802_1353'),
        ('matches', '0037_seo_league_intro_batch1'),
    ]

    operations = [
    ]
