# Generated by Django 5.0.1 on 2026-08-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0045_seo_country_intro_batch1'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_big_chances',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_big_chances',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
