# Generated by Django 5.0.1 on 2026-08-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0047_seo_league_intro_copa_brasil'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='old_slugs',
            field=models.JSONField(blank=True, default=list, help_text='Slugs antigos das URLs para redirect 301', null=True),
        ),
    ]
