BBBBBBB BBBBBBBBBBB
BBBB BBBBBB BBBBBBBBBBBBBB BBBB BBBBB

BBBBB BBBBB gettext(u'StatsFut - Football Statistics, Predictions & Match Analysis') BBBBBBBB
BBBBB BBBBBBBBBBBBBBBB gettext(u"Explore advanced football statistics, pre-match analysis, Over/Under predictions and head-to-head data for the world's top leagues. StatsFut - Your data-driven edge.") BBBBBBBB

BBBBB BBBBBB
XXX XXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXX
BBBBBBBB

BBBBB BBBBBBB


XXXX XXXXXXX XXX XXX
XXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXX
    
    XXXX XXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX BB BBBBBBBBBBBBBB BB BBBBBBBXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXBBBBXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXBBBBB XXXX XXXXXXXXXXX gettext(u'Today') XXXX
        XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX BB BBBBBBBBBBBBBB BB BBBBBBBBBBXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXBBBBXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXBBBBB XXXX XXXXXXXXXXX gettext(u'Tomorrow') XXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXBBBBXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXBBBBB XXXX XXXXXXXXXXX gettext(u'Next Round') XXXX
    XXXXXX

    XXXX XXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXX XXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Upcoming') XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Finished') XXXXXXXXX
    XXXXXX
XXXXXX

XXXXXXXX
    XXX XXXXXXXXXXXXX X XXXXXX

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
        XX XX XXXXXXX XXXX XXXXX XX XXXXXXXXX XXXXX XXXXX XXXXXX XXXXXXXXXX
        XXXXX XXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX

        XX XXXXXXX XXXXX XX XXXXX XXXXXX XXXXXXXXX XXXXXXXXX
        XX XX XXXXXX XX XXXXXX XX XXXXXXX XXX XXXXX
    XXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXX X
        XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XX XXXXX XXX XXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX

        XX XXXXXX XXXXXX XX XXXXXXXX XXXXXX XXXXXXX XXXXXX XX XXXXXX XXXX XXX XXX XXXXXXX
        XX XXXXXXXXXXX X
            XXXXXXXXXXXXX X XXXXXX
            XX XX XXXXXX XXXXXX X XXXXX XXXX
        X XXXX X
            XXXXXXXXXXXXX X XXXXXXX
            XX XXXXXXXX XXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X

        XX XXXXX XXXXXX XX XXXXX
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXX X XX

        XXXXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXX XXXXXXX
            
            XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXX X XXXXXX

            XX XXXXXXXXXXXXXX XXX XXXXXX X
                XXXXXXXXXX X XXXXX
            X XXXX XX XXXXXXXXXXXXXX XXX XXXXXXXXXXX X
                XXXXXXXXXX X XXXXXXXXXXX XXX XXXXXXXXXXX XX XXXXXXXXXX XXX XXXXXXX XX XXXXXXXXXX XXX XXXX XXXXXXXX XX XXXXXXXXXX XXX XXXXXXXXXXXXX
            X XXXX XX XXXXXXXXXXXXXX XXX XXXXXXXXXXX X
                XXXXXXXXXX X XXXXXXXXXXX XXX XXXXXXXXXX XX XXXXXXXXXX XXX XXXX XX XXXXXXXXXX XXX XXXXX XX XXXXXXXXXX XXX XXXXXXX
            X

            XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX X XXXXXXX X XXXXXXX
            XX XXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXX

        XX XXXX XXXXX XXXXXXX XXX XXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX X X X XXXXXXX X XXXXXXX
        XXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX X X X XXXXXXX X XXXXXXX
        XXX

        XX XXXX XXXXXXX XX XX XXXXX XXXXXXX
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXX XXX XX X
             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X XXXX X
             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
    X
XXXXXXXXX

XXXXXXX
    XX XXXXXX XXXXXXXX XXX XXXXXXX XX
    XXXXXXXXXXXXXXX X XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX X
    
    XX XXXXXX XXXXXXX XXXXXXXXXX XXX XX
    XXXXXXXXXXX X
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXX XXX XXXX XXXXX
    X
    XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
        XXXXXX XXXXX
    X
    XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXX XXXX XXXXXXXXXXX
        XXXXXXXXXXXX XXXXX
    X

    XX XXXXXX XXXX XXXXX XXXX XXXXXXXXX XX
    XXXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
        XXXX XXXXX
    X
XXXXXXXX


XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBB BBB BBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB
    BBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX
        XXX XXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXX XXXXXXXXXXXXXXX
            XXXXX XXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            FFFFFFFFFF
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXX
        
        BBB BBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXFFFFFFXXXXXXX  gettext(u'matches') 
                XXXXXX
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXXXX
                BBB BBBBB BB BBBBBBBBBBBBBBBBBBB
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                                BB BBBBBBBBBBBB BB BBBBBB
                                XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'LIVE') XXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                                BBBB
                                XX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
                                BBBBB
                                
                                BB BBBBBBBBBBBB BB BBBBBBBBBBB
                                    FFFFFFFFFF
                                BBBB BBBBBBBBBBBB BB BBBBBB
                                    FFFFFFFFFFFX
                                BBBB
                                    
                                BBBBB
                            XXXXXX
                            XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                                FFFFFFFFFF
                            XXXXXX
                        XXXXXX

                        XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXX XXXXXX XXX
                            XXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                                    BB BBBBBBBBBBBBBBBBBBBBBBBB
                                    XXXX XXXXXX XXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXX
                                    BBBB
                                    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXFFFFFFFFFFXXXXXX
                                    BBBBB
                                    XXXXX XXXXXXXBB BBBBBBBBBBBBBBBB B BBBBBBBBBBBBBBBBXXXXXXXXXX XXXXXXXBBBBXXXXXXXXXXBBBBB XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                XXXXXX
                                XXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                                    BB BBBBBBBBBBBBBBBBBBBBBBBB
                                    XXXX XXXXXX XXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXX
                                    BBBB
                                    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXFFFFFFFFFFXXXXXX
                                    BBBBB
                                    XXXXX XXXXXXXBB BBBBBBBBBBBBBBBB B BBBBBBBBBBBBBBBBXXXXXXXXXX XXXXXXXBBBBXXXXXXXXXXBBBBB XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                XXXXXX
                            XXXXXX
                            
                            XXXX XXXXXX XXXXXX XXX
                            XXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBB B BBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXBBBBXXXXXXXXXXBBBBBXX
                                    BB BBBBBBBBBBBB BB BBBBBBBBBBBXBBBBFFFFFFFFFFFBBBBB
                                XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBB B BBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXBBBBXXXXXXXXXXBBBBBXX
                                    BB BBBBBBBBBBBB BB BBBBBBBBBBBXBBBBFFFFFFFFFFFBBBBB
                                XXXXXX
                            XXXXXX
                        XXXXXX

                        XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXX XXXXX XX XXXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXX XXXXX XX XXXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                            XXXXXX
                        XXXXXX
                        
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXX
                BBBBBB
            XXXXXX
        XXXXXX
        BBBBBB
    XXXXXX

    XXXX XX XXXXXXXXXXX XXXXXXXXX XXX XX XX XXXXX XXXXXX XXX
    BB BBBBBBBBBBBBBBB BB B
    XXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBB

    BBBBB
    XXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXX
        XX XXXXXXXXXXXXX gettext(u'No matches found for this period.') XXXX
        XX XXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Try checking another date or filter.') XXXX
    XXXXXX
    BBBBBB
    BBBBBBBB
    
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXX
        XX XXXXXXXXXXXXX gettext(u'No matches match your filter.') XXXX
        XX XXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Try resetting the status filter.') XXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXX XX XXXX X XXX
XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXX
XXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXX XXXXX X
XXXXXXXXXXXXXXXXXXX X XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX X
XXXXXXXX

XXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
    XX XXXXXXX XXXX XXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX XX X XXXXXXXXXXXXXXX X XXXXXX XX XXXXX
    XXX

    XX XXXX XXXXXX XXXX XXXXXX XXXXXX XX XXXX
    XXXXX XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX
    XX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXX XXX XXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXX X XXXXX
                XXXXXXXXXXXXX XX X XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXX
            XXX
        XX
    X
XXX
XXXXXXXXX



BBBBBBBB
