BBBBBBB BBBBBBBBBBB
BBBB BBBBBB BBBB
BBBB BBBBBBBBBBBBBB BBBBB

BBBBB BBBBB XXXXX XXXXX X XXXXXXXX XXXXX X XXXXX X XXXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX
    XXXX XXX XX XXXXX XXX
    XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXXX XXXXXXXXXXX XXXXXXX XXX
    
XXXX XXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX XXX XXXXX XXXXXXXX XXXX XXXX XXXXXXXX
                        XX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXX
                    XXXXXX
                    XXXXX
                        XXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
                             gettext(u'Elite Statistics')  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
                        XXXXX
                        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX
                            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXX
                                XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX  gettext(u'Season') 
                            XXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX  gettext(u'Advanced metrics per match across all teams') XXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
                
                XXXX XXXXXX XXXXX XXXXXXXXX XXX XXXXX XXXX XXXX XXXXXXXX XXX
                XXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXX
                            XX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX
                        XXXXXX
                        XXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXX gettext(u'Corners (Avg)') XXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXFFFFFFFFFFFXXXXXXX
                        XXXXXX
                    XXXXXX
                    
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXX
                            XX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX
                        XXXXXX
                        XXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXX gettext(u'Yellows (Avg)') XXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXFFFFFFFFFFFXXXXXXX
                        XXXXXX
                    XXXXXX

                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXX
                            XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXX
                        XXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXX gettext(u'Total Goals') XXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXFFFFFFFFFFFXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX




    XXXX XXXXXX XX XXXXX XXX
    XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    
            
    XXXX XXXXXXXXXX XXXXX
    XXXX XXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        BBBBB BBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBB BBBBBBBBB
            XXXX XXXXXXXXXX XXX XXXXXX
                XXXX XXXXXXX XXX
                XXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX
                            XXX XXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXX gettext(u'Corners Performance Ranking') XXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XX XXXXXXXXXXX XXXXXXXX XXXXXXXX XXXX
                                        XXX XXXXXXXXXXXXXXXXXXXXXXX
                                            XXX XXXXXXXXXXXXXXXXX XXXXXX gettext(u'Team') XXXXX
                                            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX gettext(u'For') XXXXX
                                            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX gettext(u'Against') XXXXX
                                            XXX XXXXXXXXXXXXXXXX XXXXXX gettext(u'Total') XXXXX
                                        XXXXX
                                    XXXXXXXX
                                    XXXXXXX
                                        BBB B BB BBBBBBBBBB
                                        XXXX
                                            XXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
                                                BB BBBBBBBBBBBBBBB
                                                XXXX XXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXX
                                                BBBBB
                                                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
                                                    
                                                XXXX
                                            XXXXX
                                            XXXXXXXXX
                                            XXXXXXXXX
                                            XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
                                        XXXXX
                                        BBBBB
                                        XXXX
                                            XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX
                                                XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX
                                                 gettext(u'No data available.') 
                                            XXXXX
                                        XXXXX
                                        BBBBBB
                                    XXXXXXXX
                                XXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX  gettext(u'Ranking of teams with the most corners on average per match (For, Against and Total).') XXXXXXX
                    XXXXXX
                    XXXXXX
                XXXXXX
                
                XXXX XXXXX XXX
                XXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX
                            XXX XXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXXXXX gettext(u'Cards & Discipline Ranking') XXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XX XXXXXXXXXXX XXXXXXXX XXXXXXXX XXXX
                                        XXX XXXXXXXXXXXXXXXXXXXXXXX
                                            XXX XXXXXXXXXXXXXXXXX XXXXXX gettext(u'Team') XXXXX
                                            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX gettext(u'Yellow') XXXXX
                                            XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXX gettext(u'Red') XXXXX
                                        XXXXX
                                    XXXXXXXX
                                    XXXXXXX
                                        BBB B BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                                        XXXX
                                            XXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
                                                BB BBBBBBBBBBBBBBB
                                                XXXX XXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXX
                                                BBBBB
                                                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
                                                    
                                                XXXX
                                            XXXXX
                                            XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                            XXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
                                        XXXXX
                                        BBBBB
                                        XXXX
                                            XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX
                                                XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX
                                                 gettext(u'No data available.') 
                                            XXXXX
                                        XXXXX
                                        BBBBBB
                                    XXXXXXXX
                                XXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX  gettext(u'Disciplinary ranking showing the teams with the most yellow and red cards per match.') XXXXXXX
                    XXXXXX
                    XXXXXX
                XXXXXX
        
                XXXX XXXXX XXX
                XXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX
                            XXX XXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX gettext(u'Shots per Match') XXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XX XXXXXXXXXXX XXXXXXXX XXXXXXXX XXXX
                                        XXX XXXXXXXXXXXXXXXXXXXXXXX
                                            XXX XXXXXXXXXXXXXXXXX XXXXXX gettext(u'Team') XXXXX
                                            XXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX gettext(u'Shots (Avg)') XXXXX
                                        XXXXX
                                    XXXXXXXX
                                    XXXXXXX
                                        BBB B BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                                        XXXX
                                            XXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
                                                BB BBBBBBBBBBBBBBB
                                                XXXX XXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXX
                                                BBBBB
                                                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
                                                    
                                                XXXX
                                            XXXXX
                                            XXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
                                        XXXXX
                                        BBBBB
                                        XXXX
                                            XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX
                                                XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX
                                                 gettext(u'No data available.') 
                                            XXXXX
                                        XXXXX
                                        BBBBBB
                                    XXXXXXXX
                                XXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX  gettext(u'Ranking of teams with the highest average number of shots per match.') XXXXXXX
                    XXXXXX
                    XXXXXX
                XXXXXX
        
                XXXX XXXX XXXXXX XXX
                XXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX
                            XXX XXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXXX gettext(u'Goal Minutes Distribution') XXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXX XXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXX
                                    XXXXXXX
                                        XXX XXXXXXXXXXXXXXXXXXXXXXX
                                            XXX XXXXXXXXXXXXXXXXX XXXXXX gettext(u'Period') XXXXX
                                            XXXX gettext(u'Goals') XXXXX
                                            XXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
                                        XXXXX
                                    XXXXXXXX
                                    XXXXXXX
                                        BBB B BB BBBBBBBBBBBB
                                        XXXX
                                            XXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXX
                                            XXXXXXXXX
                                            XXX XXXXXXXXXXXXXXX XXXXXX
                                                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX
                                                    XXXXXXFFFFFFFFFFFFFXXXXXXXX
                                                    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXXX
                                                         XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                                                     XXXXXX
                                                XXXXXX
                                            XXXXX
                                        XXXXX
                                        BBBBBB
                                    XXXXXXXX
                                XXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX  gettext(u'Distribution of goals scored across 15-minute periods of the match.') XXXXXXX
                    XXXXXX
                    XXXXXX
                XXXXXX
        
                XXXX XXX XXXXXXX XXX
                XXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX
                            XXX XXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXXXXX gettext(u'League Top Scorers') XXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XX XXXXXXXXXXX XXXXXXXX XXXXXXXX XXXX
                                        XXX XXXXXXXXXXXXXXXXXXXXXXX
                                            XXX XXXXXXXXXXXXXXXXX XXXXXX gettext(u'Player') XXXXX
                                            XXXX gettext(u'Team') XXXXX
                                            XXX XXXXXXXXXXXXXXX XXXXXX gettext(u'Goals') XXXXX
                                        XXXXX
                                    XXXXXXXX
                                    XXXXXXX
                                        BBB B BB BBBBBBBBBBB
                                        XXXX
                                            XXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                                            XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                            XXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXX
                                                
                                                BB BBBBBBBBBBB B B
                                                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
                                                BBBBB
                                            XXXXX
                                        XXXXX
                                        BBBBB
                                        XXXX
                                            XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX
                                                XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX
                                                 gettext(u'No data available.') 
                                            XXXXX
                                        XXXXX
                                        BBBBBB
                                    XXXXXXXX
                                XXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX  gettext(u'League top scorers for the current season, including penalty goals.') XXXXXXX
                    XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        BBBBBBBB
    XXXXXX
    
    XXXX XXXXXXX XXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXX XXXXXX XXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
            XXXXXXXX X XXXXXXX
        XXXXXX
    XXXXXX
XXXXXX
    
    XXXX XXX XXXX XXXX XXXXXXXX XXX
    XXXX XXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX
                    XXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
                        XX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX gettext(u'Detailed Statistics and Elite Analysis') X 
                    XXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
                    XX XXXXXXXXXXXXX
                         gettext(u'Advanced statistics and detailed analysis for the %(league_name)s (%(country)s) league, %(year)s season. Explore in-depth information about corner averages, distribution of yellow and red cards per game, team discipline, volume of shots, and the exact moment goals happen throughout the 90 minutes.') SSSSSSSS SSSSSSSSSS SSS SSSSSSSS SSSSSSSS SSS SSS SSSSSSSSSSSSSSS SSSSSSSSSSSSS SSSSSSS SSSSSSSS SSSSSSS SSSSSSS SSSSSSSS SSSSSSSSSSS SSSSS SSSSSS SSSSSSSSS SSSSSSSSSSSS SS SSSSSS SSS SSS SSSSS SSS SSSSS SSSS SSSSSSSSSSS SSSSSS SS SSSSSS SSS SSS SSSSS SSSSSS SSSSS SSSSSS SSSSSSSSSS SSS SS SSSSSSSS
                    XXXX
                    BB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXXXX
                         gettext(u'So far, the overall championship average records %(avg_corners)s corners taken per match and a disciplinary average of %(avg_yellow)s yellow cards received per game. This data provides a complete overview of the tactical behavior trends and game intensity of each team in the competition.') SS SSSS SSS SSSSSSS SSSSSSSSSSSS SSSSSSS SSSSSSS SSSSSSSSSSSSSSS SSSSSSS SSSSS SSS SSSSS SSS S SSSSSSSSSSSS SSSSSSS SS SSSSSSSSSSSSSS SSSSSS SSSSS SSSSSSSS SSS SSSSS SSSS SSSS SSSSSSSS S SSSSSSSS SSSSSSSS SS SSS SSSSSSSS SSSSSSSS SSSSSS SSS SSSS SSSSSSSSS SS SSSS SSSS SS SSS SSSSSSSSSSSS
                    XXXX
                    BBBBB
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXX XX XXXXX XXX
    XXXX XXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX

XXXXXXX
    XX XXXXXXX XXXXX XX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX XXXXXXX X
    XXXXXXXXXXXXX X XXXXXXXXXXXX XXXX X
    XXXXXXXXX X XXXXXXXXXXXX XXXX X
    
    XXXXXXXXXXXXXXX X XXXXXX XXXXXXXX X
    XXXXXXXXXXXXXXX X XXXXXX XXXXXXXX X
    XXXXXXXXXXXXXXX X XXXXXX XXXXXXXX X
    
    XX XXXXXX XXXXXX XXXXX XX
    XXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XX XXXX XXX XXXXXXXXXX XXXX XXXXX XXXXXXXXXXXX XXXX XXXXX
        XXXXXXXXXXX X XXXX XXXX XXXXXXX XX XX XXXXX
    X
    
    XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXX X XXXX XXXX XXXXXXX XX XX XXXXXX
        XXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXX
    X
    
    XXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
        XXXXXXX XXX XXXXX XXXXXXXX XXXX XXXX XXXXXX
    X

    XX XXXXXX XXXXX X XXXXX XXXXXXX XXXXXX XXXXX XX
    XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXX XXXXXX XXXXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXX XXXXX
        XXXXXXXXXX XXXXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXX
        XXXXXXXXXXX XXXXXXXX
    X
    
    XX XXXXXXX XXXX XXXXX XXXXXX XX
    XXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXXX
        XXXXXXXXXXX XXXXXXXXX XXXX XXXXX XXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXX XXXX XXXXX
    X
    XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
    X
    
    XX XXXX XXXXXXXX XXXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXX X
        XXXXXX XXXXX
        XXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXX XXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXX
        XXXXXXX XXX XXXXX XXXXXXXX XXXX XXXX XXXXX
        XXXXXX XXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXXX XXXXX X XXX XXX XXXXXXXXXXXXXXXX
    X

    XX XXXXXXX XXXX XXXXXXXX XXXX XXXXX XXXXX XXXXX XX
    XXXXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXX
        XXXXXXX XXXXX
        XXXXXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXX XXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXX
        XXXXXXX XXX XXXXX XXXXXXXX XXXX XXXX XXXXX
        XXXXXX XXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXXX
    X
    
    XX XXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXX XX
    XXXXXXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXX XXXXXXX
        XXXXXXXXXX XXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXXX
        XXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXX X XXX XXX XXXXXXX XX XX XXXXX
    X
    XXXXXXXXXXXXXXXX XXXXXX X
        XXXXXXXX XXXXXXX XXXXXXXX
        XXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXX XXXXXX
    X
    XXXXXXXXXXXXXXXX XXXXXX X
        XXXXXXXX XXXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXX XXXXX
        XXXXXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXX
    X

    XX XXXXXXX XXXX XXXXXX XXXX XXXXX XXXXX XXXXX XX
    XXXXXXXXXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXX XXXXXXX
        XXXXXXXXXX XXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXXX
        XXXXXXXXXXX XXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXX XXXXXX X
        XXXXXXXX XXXXXX XXXXXXX
        XXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXX XXXXXX
    X
    XXXXXXXXXXXXXXXXXXX XXXXXX X
        XXXXXXXX XXXXXX XXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXX XXXXX
        XXXXXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXX
    X
    
    XX XXXX XXXXX XXXXXX XXXXXXX XXXXXXXX XX XXXXXXXXX XXXXXXXXXXX XX XXXXXXXXXX XX
    XXXXXXXXXX X
        XXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXX
    X
    XXXXXXXXXX XXXXXX X
        XXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXX
        XXXXXX XXXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXX X
        XXXXXXXXXXXXX XXXXXXXXX XXX XXX XXXXXX
    X
    XXXXXXXXXXXXXX XXXXXX X
        XXXXXXXXXXX XXXXXXXXX XXX XXX XXXXXX
        XXXXXX XXXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXX X
        XXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXX
    X
    XXXXXXXXXXXX XXXXXX X
        XXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXX
        XXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXX
    X

    XX XXXXX XXXXX XXXXX XXXXXXXXXXX XXXXXXX XXXXXX XX
    XXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXX XXXXXXX
        XXXXXXXXXX XXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXXX
        XXXXXXXXXXX XXXXXXXX
    X
    XXXXXXXXXX XXXXXXXXXXX X
        XXXXXXXX XXXXXXX XXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXX XXXXXXX
    X
    XXXXXXXXXX XXXXXXXXXXX X
        XXXXXXXX XXXXXXX XXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXX XXXXX
        XXXXXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXX
    X
    XXXXXXXXXXXXX X XXXXXX XXXXXXXX X
    XXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXX XXXX XX XXXXXX XXXXXX XXXXXXX XXXXXXXXXXX X
    
    XXXXXXXXXX X XXXXXX XXXXXXXX X
    XXXXXXXXXX X XXXXXXXXXXX XXXXXXXXX XXX XXX XXXXXX XXXXXX XXXXXXX XXXXXXXXXXX X

    XX XXXX XXXXXXXXX XX
    XXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
    X

    XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
    X
    
    XXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXX XXXX XXXXX
    X
    XXXXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXX XXXXXXXXXXX
    X

    XX XXXXXXXX XXXX XXX XXXXXX XX
    XXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
        XXXXXXX XXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXX XXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXXX
    X

    XX XXXXXXXXXX XXXXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXX XXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
        XXXXXXXXXXXXXX XXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
    X

    XX XXXXXX XXXXXXXXXX XX
    XXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX
    X
    XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXX
    X
    
    XXXXXXXXX X XXXX XXXXXXXX XXXXXXXXXXX X
XXXXXXXX
BBBBBBBB
