BBBBBBB BBBBBBBBBBB
BBBB BBBBBB BBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXX X XXXXXXXX XXX
    XXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Live') XXXXXXX
                    XXXXXXX
                XXXXXXX
                 gettext(u'Live Matches') 
            XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search leagues, teams...') XX
            XXXXXX
        XXXXXX
    XXXXXX

    BB BBB BBBBBBB
    XXXX XXXXX XXXXX XXX
    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXX
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'No live matches currently') XXXXX
            XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Check back later or view upcoming fixtures in the dashboard.') XXXX
            XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXX XXXXXXXXXXXX XXXXXX gettext(u'Go to Dashboard') XXXX
        XXXXXX
    XXXXXX
    BBBB

    XXXX XXXX XXXXXXX XXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        BBB BBBBBBBBBBBB BBBB BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXFFFFFXX
            XXXX XXXXXX XXXXXX XXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXX XXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                    BB BBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXFFFFFFFFFFFFFFFFFFFFFFX XXXXXFFFFFFFFFFX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXX
                    BBBBB
                    XXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXFFFFFF  gettext(u'Live') XXXXXXX
            XXXXXX

            XXXX XXXXXXX XXXX XXX
            XXXX XXXXXXXXXX XXX XXXXXX
                BBB BBBBB BB BBBBBBBBBBBB
                XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXFFFFF FFFFFXX
                    XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX
                        XXXX XXXXXXXXXXXXXXXX XXXX XXXXXX
                            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXX XXX
                                XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX
                                    XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXX
                                        BB BBBBBBBBBBBB BB BBBBBB gettext(u'LIVE') BBBBBBBBB
                                    XXXXXX
                                    XXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX

                                XXXX XXXXX X XXXXXX XXX
                                XXXX XXXXXXXXXXXXX XXXXXX
                                    XXXX XXXX XXX
                                    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                                        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
                                            XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                                        XXXXXX
                                        XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXX
                                    XXXX XXXX XXX
                                    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
                                            XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                                        XXXXXX
                                        XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXX
                                XXXXXX
                            XXXXXX
                        XXXXXX
                        XXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXX XXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                BBBBBB
            XXXXXX
        XXXXXX
        BBBBBB
    XXXXXX
    BBBBB
XXXXXX

XXXXXXX
    XXXXXXXXXXXXXX X XXXXXXXXXXXXXXX XXXXXXX X
    XXXXXXXXXXXXXX X XXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
    XXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXX X
    XXXXXXXXXXXXXXXXX X XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
    XXXXXXXXXXX X XXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXX X
    XXXXXXXXXXXXXXXX X XXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXX X
    
    XXXXXXXXXX XXXXXXXXX X
        XX X XXXXXXXXXXX X X X X XXXXXXXXX XXX XXX XXXXX X
        XXX X XXXXXXXXXXX X X X XXX XXXXXXXXX XXX XXX XXX X
        XXXX X XXXXXXXXXXX X X X X XXXXXXXXX XXX XXX XXX X
    X
    
    XXXXXXXXXX XXXXXXXXXX X
        XX X XXXXXXXX XX X
        XXX X XXXXXXXX XXXX X
        XXXX X XXXXXXXX XX X
    X
XXXXXXXX

XXXXXXXX
XX XXX XXXXXX XX XXXXX XXX
XXXXXXXX XXXXXXXXXXXXXXXXXXX X
    XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX X XXXXXX
        
        XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XXXXXXXXXXXXXXXXXXXXX XX X
            XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXX X XXXXX
            X XXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        XXX
        
        XX XXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X XXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
    XXX
X

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX

XX XXX XXXXXXXXXXX XXXXXXXXXX XXXXXX XXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
        XXXXXXXXXX XX X
            XX XXXX XX XXXXXXXX XXXXXXXXXX XXXX XXXXXXX X XXXX XXXX
            XXXXX XXXXXX X XXX XXXXXXXXXXXX
            XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            
            XX XXXX X XXXX XXXXXXXXX XX XXXXX
            XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
            XX XXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX X
                XX XXXXXXXXX X XXXX XXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
                
                XX XXXXXXXX X XXXXXX XX XXXXX XXXX X XXXXXXX XXXXXX XXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXX
            X XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                 XX XX XX XXXXX XXXXXXXX X XXXXXX XXXX X XXXX XXXXX
                 XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 XX XXXXXXXX X XXXXXX XXXX XXXX XXXXXXX X XXXX XXXXX XXXXXXXXXXXX XX XXXXXXXXXX
                 XXXXXXXXXXXXXXXXXXXXXXXXX
            X
        XX
        XXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX XX XXXXXXXXX XXXXX XX XXXXXXX XXXXXX
X

XX XXXXXXXX X XXXX XX XXXXXXXX XXXXXX XXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX

XXXXXXXXX
BBBBBBBB