BBBBBBB BBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBB
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXX BB BBBBBBBBBBBB BB BBBBBBXXXXBBBBBXXXXXXXXX
    XXXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXX XXXXXX X XXXXX XXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXFFFFFFFFFFXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBB BB BBBBBBBBBBB
                XXXXX XXXXXXXXXXXXXXXXXXXX
            BBBB
                XXXXX XXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXX
            BBBBB
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXFFFFFFFFFFXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX

    BB BBBBBBBBBBBBBB
    
    XXXX XXXX XXXXXXXX XXXXX XXXXX XX XXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XX XXXX X XXXXX X XXXX X XXXXXXXX X XXXXXX X XXXX XXX XX
        XXXXXX
        
        XXXX XXXXXXXXXXXXXXXXXXX
            
            XXXX XXXXX XX XXXXX X XXXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXX XXX X XXX XXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX

                XXXX XXXXXXX XXXXXXXXX XXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
                            XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
                            XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB B BBXXXX XXXBBBBXXXXX XXXBBBBBXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB B BBXXXX XXXBBBBXXXXX XXXBBBBBXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX

                XXXX XXXX XXX X XXX XXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX

            XXXX XXXXX XX XXX XXXX X XXXXXX XXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXX XXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX

                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXXXX
                            XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXX FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX

                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXX XXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX XXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXX XXXXXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX

        XXXXXX
    XXXXXX

    XXXX XX XXXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XX XXXXXXXXXX
        XXXXXXX
    XXXXXX

    XXXX XXXXXX XXXXX XXXXXXXX X XXXXX XXX
    XXXX XXXXXXXXXX XXXX XXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BBB BB B BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXX
                    XXXXXX
                    BBBBBB
                XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                        XXXXXXFFFFFFFFFFFFFFFFXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXXFFFFFFFFFFFFFFFFXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

    BBBBB

XXXXXX

XXXXXXX
    XX XXXXXXXXXXX XX X XXXXX XXXX XXXXXXX XX
    XXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXX
    X

    XXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXX XX
    X

    XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXX
        XXXXXXX X XXXXX
        XXXXXXXX XXXXX
    X

    XX XXXXXX XX
    XXXXXXXXXXXXXXX X
        XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXXX XXXX XX
    X
    XXXXXXXXXXXXXXXXX X
        XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXX
    X
    XXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXX XXXX
        XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX
    X
    XXXXXXXXXXX X XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX X
    XXXXXXXXXXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXX XXXXXXXXX X

    XX XXXX XX
    XXXXXXXXXXXXXXXXXXX X
        XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
        XXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX
    X
    XXXXXXXXXX X XXXXXXXXXXX XXXXXXX X
    XXXXXXX X
        XXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX
        XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXX XXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX
    X
    XXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXX X
    XXXXXXX X XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXX X
    XXXXXXXXXXX X XXXXXXXXXX XXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXX X
    XXXXXXXXXXX XXX X XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXX X

    XX XXXXXXXX XXXXX XXXX XXXXX XXXXX XX
    XXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXX XXX XXXXX XXXXXXXX
        XXXXXXXXX XXXXXXX
    X
    XXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX XXXXXX XXXXX XXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXX
        XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXX
    X
    XXXXXXXXXXX X XXXXXXXX XXXXX X

    XXXXXXXXXXXXXX X XXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXX XXXXX XXXX XXXX XXXXX XXXXXXXXXXXX XXXXXXX X
    
    XXXXXXXXXXX X XXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX X
    XXXXXXXXX X XXXXXXXXXXX XXXXXXX X
    XXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXX XXXXXX XXXXX XXXXXXXXXXXX XXXX XXXXXXXX XXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXX XXX XXXXXXXXX XXXXXXXXX XXXXXXX XXXXX XXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXX XXXXX XXXXX
    X
    XXXXXXXXXXXXXX X XXXXXX XXXXXX XXXXXXX XXXXXX X
    XXXXXXXXXXX X XXXXXXXXXX XXXXXXXXXXXXXXX X
    XXXXXXXXXXX X XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XX X
    XXXXXXXXXX X XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XX XXXXXXXXXXXXXXX XXXXX X
    XXXXXXXXXX X XXXXX XXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXX X

    XX XXXXXXX XXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXX X
    XXXXXXXXXXX X XXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXX X
    XXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXX XXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX X XXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXX X
    XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX XX X
    XXXXXXXXXX XXXXXXX X XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX X
    XXXXXXXXXX XXXXX X XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXX X
    XXXXXXXXXX XXXXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXX XXXX X XXXXXX XXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXX XXXXX XX XXXXXXXXXXXX XXXXX X

    XX XXX XXX XX
    XXXXXXXXXXXXXX X XXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXX XXX XXXXXX XXXX XXXXX XXXXXXXXXXXX XXXXXXXXX X
    XXXXXXXXXX X XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXX X
    
    XXXXXXXXXXXXX X XXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX X
    XXXXXX X XXXXXXXXXXX XXXXXXX X
    XXXXXX XXXX X XXXXXXXX XXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXX XXXX X
    XXXXXX XXXX X XXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX X

    XXXXXXXXX X XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXX X
    XXXXXXXXXX X XXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXXXXXX X
    XXXXXXX X XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX X
    XXXXXXXX X XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXX X
    XXXXXXXXXXX X XXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX X
    XXXX X XXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX X
    XXXXXXXXXX X XXXXXXXXXXX XXXXX X
    XXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXXXX X

    XX XXXXXX X XX XXXX XX
    XXXXXXXXXXXXX X XXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
    XXXXXXXXX X XXXXXXXXXXX XXXXXXX X
    XXXXXXXXX XX X XXXXXXXX XXXXXX XXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX X
    XXXXXXXXX XXXXXX X XXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX X

    XXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
        XXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXX XXXX
        XXXXXXXXXXX X X XXXX XXXXXXXX XXXX XXXX XXXXX
        XXXXXXXXXXX XXXXXXX XXXXXXX XXX XXXXX XXXXXXXX
    X
    XXXXXXXXX X XXXXXXXX XXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXX X
    XXXXXXXX X XXXXXXXX XXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXX XXXXX X
    XXXXXXXX X XXXXXXXX XXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXX X

    XX XX XXXXX XX
    XXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXX
    X
    XXXXXXXXXX X XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX X
    XXXXXXXXXXXXXXXX X X XXXXXXX XX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX X

    XX XXXXXX XXXXXX XX
    XXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXX
    X
    XXXXXXXXXXXXXXXXX X XXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX X
    
    XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X
    XXXXXXXX X XXXXXXXXXXX XXXXXXX X
    XXXXXXXX XX X XXXXXXXX XXXXXX XXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXX X
    XXXXXXXX XX X XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXX X

    XXXXXXXXX X XXXXXX XXXX X
    XXXXXXXXX XXXX X XXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX X
    XXXXXXXX X XXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXX X
    XXXXXXXX XXXXX X XXXXXXX XXXXX XXXXXXXXXXXXXX XXXX X
    XXXXXXXX XXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X
    XXXXXXXX XXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X

    XXXXXXXXXX XXXXX X XX X XXXXXXXX XX X XXX X XXXXXXXX XXXX X XXXX X XXXXXXXX XX X X

    XXXXXX XXXXXXXXXXX XXXXXX X
        XXXXXXXXXXXXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXX X
        XXXXXXXXXXXXXXXXXXX X XXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX X
        XXXXXXXXXXXXX X XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXX X
    X
XXXXXXXX
BBBBBBBB