BBBBBBB BBBBBBBBBBB
BBBB BBBBBB BBBB BBBBBBBBBBBBBB

BBBBB BBBBB XX  X XXXXX XXXXX X XXXXXXXXBBBBBBBB
BBBBB BBBBBBBBBBBBBBBB XX  XXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXX XXX XXXXXXXXXXXX XBBBBBBBB
BBBBB BBBBBBBB XX  X XXXXX XXXXX X XXXXXXXXBBBBBBBB
BBBBB BBBBBBBBBBBBBB XX  XXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXX XXX XXXXXXXXXXXX XBBBBBBBB

BBBBB BBBBBB
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
XXXXXXX
    XX XXX XXXXXXXXXX XXXX XXXXXXXX XX
    XXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXX XXXXXXX
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXX XXXXX XX XXXXXXX XX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXX X
    XXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
        XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXX
        XXXXXXXX XXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXX XXX XXXX XXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXX XXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
        XXXXXX XXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX
        XXXXXX XXXXX
        XXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXXX XXXX XXXX XXXXX
    X
    XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXX XXXX XXXX XXXXXXXXX
    X
    XXXXXXXXXX XXXXXX X
        XXXX X XXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXXX X
        XX X XXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXX X
    X
    
    XX XXXXXX X XXXXXXXX XXX XX
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
        XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXX XXXXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXX XXX XXXX XXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXX
    X
    XXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXX XXXXXX XX
        XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXXXX
    X
    XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX XXXXX X
    XXXXXXXXXXXXXX X XXXXXXXXXXXX XXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXX X
    XXXXXXX XXXXX X XXXXXXXXXXXX XXXX XXXXXX XXXXXXXX X
    XXXXXXX XXXXXXXXXX X XXXXXX XXXXXXXX X
    XXXXXXX XXXXXXXXX X XXXXXX XXXXXXXX X
    
    XXXXXXXX X XXXXXXXX XXXXX XXXX XXXXX XXXXXXXXXXX XXXXXXX XXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX X
    XXXXXXXX X XXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXX XX X
    XXXXXXXX XXXXXXX X XXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX X
    XXXXXXXX XXXXX X XXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXX X
    XXXXXXXX XXXXXXXXXX X XXXXXX XXXXXXXX X

    XXXXXXXXXXXXX X
        XXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXX XXXXXX XXXXXXXX
    X
    XXXXXXXXXXXXX XXXXXX X XXXXXX XXXXX X

    XX XXXXXXXXX XXX XXXXX XXXXXX XXX XX
    XXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
        XXXX XXXXX
    X
    XXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
        XXXX XXXXX
    X
    XXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXX
        XXXX XXXXXXX
    X
    XXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXXXX XXXXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXX XXXXXXX
    X
    XXXXXXXXXX XXXXXX X XXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXX X
    XXXXXXXXXX XXXX X XXXXXXXXXX XXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXX X
    XXXXXXXXXX XXXXXXXXX X XXXXXX XXXXXXXX X

    XXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXXXX
        XXXXXXXX XXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXXX XXXXXXXX
    X
    XXXXXXXXXXX XXXXXXXXXXXXX X XXXXXX XXXXXXXX XXXXXXXXXXXX XXXX X
    XXXXXXXXXXX XXXXX X XXXXXXXXXXXX XXXX XXXXXX XXXXX XXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXX XXXXXXX XXX XXXXX XXXXXXXX XXXX XXXX XXXXX XXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXXX X
    XXXXXXXXXXX XXXXXXXXXX X XXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXX XXXXXX XXXXXXXX X

    XXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXX
        XXXXXXXXXXX XXXXXXXXX XXX XXXX XXXXXX
        XXXXXX XXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXX XXXX XXXXX
        XXXXXXXX XXX XXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXX
    X

    XXXXXXXXXXXXXX X
        XXXXXXX XXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXX XXXXXXX
        XXXXXXXXXXX XXXX
    X
    XXXXXXXXXXXXXX XXXXX X
        XXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
        XXXXXXXXXXXXXX XXXX
    X

    XX XXXXX XX XXXXXXX XX XXXXX XX XX
    XXXXXXXXXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXX XXXXXX
        XXXX XX
        XXXXX XX
        XXXXXX XXXXX
        XXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXX XX
        XXXXXXXXXXX XXXXXXX XXXX XXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXX XX
    X
    XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXX XXXX XXXXX
        XXXXXXXXXXX X XXXX XXXX XXXXXXXXX XXX XXXX XXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXX XXXX
        XXXXXXXXXX XXXXXX
        XXXXXXXXXXX XXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXX XXXXXXX
        XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XX XXXX XX XXXXXXXXX
    X
    XXXXXXXXXX XXXXXXXXXXXX X
        XXXX X XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XX X
        XX X XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XX X
    X
    XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXX XXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
    X
    XXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXX XX
        XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXX XXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXX XXXXXXX
    X
    XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXX
        XXXXXXX XXXXX
        XXXXXX XXXXXXXX
        XXXXXXXXXX XXXXXXX
        XXXXXXX XXXXXXXX
        XXXXXXXXXXX XXXXX XXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXX XXXXX
    X
    XXXXXXXXXXXXXXXXXX X
        XXXXXXXX XXXXXXX
        XXXXXXXXXXX XXXXX
        XXXXX XX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXX XXXXXXX
        XXXX XXXXX
        XXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXX
    X
    XXXXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXX
        XXXX XXXXX
        XXXXXXXX XXXX XX
    X
    XXXXXXXXXXXXXXXX X
        XXXXXX XXXXX
        XXXXXXX XXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXX XXXX XXXXX
        XXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXXX XXXX XX XXXXXX XXXXXXXXX
    X
    XXXXXXXXXX XXXX X
        XX X XXXXXXXXXX XXXXXXXXXXXXXXX X
    X
    XXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXX XXXXXXX
        XXXXXX XXXXXXXX
        XXXXXXX XXXXX
        XXXXXXX XXXXXX
        XXXXXX XXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXX XXXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXX XXXX XXXXXXX
        XXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXX
        XXXX XXXXXXX
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
    X
    XXXXXXXXXXXXXXXXXX X
        XXXXXXXX XXXXXX XXXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXX XXXXXXXX
        XXXXXXX XXXXXXXX
        XXXXXXXXXXX XXX XXXXX
        XXXXXXX XXXXX
    X
    XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXX
    X
    
    XX XXX XXXXX XXXXXXXX XXX XXX XX
    XXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX XXX XXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXX XXXXXXX
        XXXXXXXXXXX X XXXX XXXX XXXXXXX XX XX XXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXX XXXXXXXXX XXXX XXXXX XXXXXXXXXXXX XXXX XXXXX
    X
    XXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXX XXXXXXXXX XXX XXXX XXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
    X
    XXXXXXXXXXXXX X
        XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXX
        XXXXXX XXXXXXXX
        XXXXXXXXXXXXXX XXXXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXX XXXXXXX
        XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXX XXXX XXXX XXXXXX
        XXXXXXXXXXXXXXX XXXXXXX
    X
    XXXXXXXXXXXXX X X XXXXXX XXXXXXXX X
    
    XXXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
        XXXX XXXXX
    X
    XXXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXX
    X
    
    XX XXXXXXXXXX XXXXXXXX XXXX XX
    XXXXXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXX XXXXXXX
        XXXX XXXXXXX
    X
    XXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXX XXXXXXX
        XXXX XXXX
    X
    XXXXXXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXX XXXXXXXX
    X
    XXXXXXXXXXXX XXXX X XXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXX
    XXXXXXXXXXXX XXXXXXXXX X XXXXXX XXXXXXXX X
    XXXXXXXXXXX X
        XXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXX XX XX XXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXX XXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX
    X
    XXXXXXXXXX X
        XXXXXXX XXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXXXXX XXXXX XX XXXXXXXXXXXXXXXXX XX XXXX XXX
    X
    XXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX X
    XXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX X
    XXXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX X
    XXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX X
    XXXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX X
    
    XX XXX XXXXX XXXXX XX
    XXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXX
        XXXXXXX XXX XXXXX XXXXXXXX XXXX XXXX XXXXX
        XXXXXX XXXXXXXX
        XXXXXXXX XXX XXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXX
        XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXX
    X
    
    XX XXXX XXXXXXX XX
    XXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXXX
        XXXXXXXX XXXXX
        XXXXXXXX XXXXX
        XXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXX XXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX
    X
    XXXXXXXXXXXX XXXXXX X XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX X
    XXXXXXXXXXXX XXXXXX X XXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX X
    XXXXXXXXXXXX XXXX X XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXX XXXX X
    
    XX XXX XX XXX XXXXX XXXX XX
    XXXXXXXX X
        XXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXX XXXXX
        XXXXXXXXXXXXXX XXXXXXX
    X
    XXXXXXXXX X XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXX XXXXXX XXXXX X
    XXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXX X
    XXXXXXXXXXXXXX X XXXXXXXXXXX XXXXX X
    XXXXXXXXXX X
        XXXXX XX
        XXXXXXX XXXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX XXXX
        XXXXXXXX XXXXX
        XXXXXXXXX XXXXXXX
        XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX
    X
    XXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX X
    XXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX X
    XXXXXXXX X XXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXX XXXXXX XXXXX XXXXXXXXXXX XXXXXXX X
XXXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXX BB BBBBBBBBBBBB BB BBBBBBXXXXBBBBBXXXXXXXXX
    XXXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXX XX XXXXX XXX
    XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXX XXXXXX X XXXXX XXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXX
            BBBB
            XXXX XXXXXXXXXXXXXXXFFFFFFFFFFXXXXXX
            BBBBB
            XXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBB BB BBBBBBBBBBB BB BBBBBBBBBBBBBBBB BB BBBB BB BBBBBBBBBBBBBBBB BB BBBB
                XXXXX XXXXXXXXXXXXXXXXXXXX
            BBBB
                XXXXX XXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXX
            BBBBB
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXX
            BBBB
            XXXX XXXXXXXXXXXXX XXXXXXFFFFFFFFFFXXXXXX
            BBBBB
            XXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX
    
    XXXX XXX XXXX XXXXXXX XXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
        XX XXXXXXXXXXXXX
             gettext(u'Complete statistics, predictions, and detailed analysis for the match between <strong>%(home)s</strong> and <strong>%(away)s</strong>, valid for the <strong>%(league)s</strong>. Analyze the probabilities of Both Teams to Score (BTTS), Over 2.5 Goals, corners, cards, and head-to-head (H2H) history to support your data-driven sports analysis.') SSSSSSSS SSSSSSSSSSS SSSSSSSSSSSS SSS SSSSSSSS SSSSSSSS SSS SSS SSSSS SSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSS SSS SSSSSSSSSSSSSSSSSSSSSSSSSS SSSSS SSS SSS SSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSS SSS SSSSSSSSSSSSS SS SSSS SSSSS SS SSSSS SSSSSSS SSSS SSS SSSSSS SSSSSSSS SSSSSS SSS SSSSSSSSSSSS SSSSS SSSSSSS SS SSSSSSS SSSS SSSSSSSSSSS SSSSSS SSSSSSSSS
        XXXX
    XXXXXX
    
    XXXX XXXXX XXXXXX XXXXX XXXXX XXX
    BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBB BB BBB BBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'TIMELINE') XXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'MATCH STATS') XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                BBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBB BB BBBBBBBBBBBBBBBXXXXBBBBXXXXBBBBBXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXBBBBB
                        BB BBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXBBBBB
                    XXXXXX
                XXXXXX
                BBBBB
                XXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXX gettext(u'No goal events recorded') XXXXXX
                BBBBBB
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXX gettext(u'Corner Kicks') XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXX XXXXXXXXXX
                        XXXX XXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXX XX XXXXXXXXXXXXX XXXXXXXXXXXX
                        XXXXXX
                        XXXXX XXXXXXXX XXXXXXXXXX
                    XXXXXX
                XXXXXX
                BBBBBBB

                BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXX gettext(u'Total Shots') XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXX XXXXXXXXXX
                        XXXX XXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXX XX XXXXXXXXXXXXX XXXXXXXXXXX
                        XXXXXX
                        XXXXX XXXXXXXX XXXXXXXXXX
                    XXXXXX
                XXXXXX
                BBBBBBB

                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXX gettext(u'Yellow Cards') XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXX XXXFFFFFFFFFXXXXXXX
                        XXXX XXXXXXXXXXXX XXXXXXXXXX
                            XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                        XXXXXX
                        XXXXX XXXXXXXX XXXFFFFFFFFFXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    BBBBB


    BB BBBBBBBBBBBBBB
    
    XXXX XXXX XX XXXX XX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX  gettext(u'Gols & Tempos') XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX  gettext(u'Escanteios') XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Cartões') XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX  gettext(u'Chutes') XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX  gettext(u'Especiais & Combos') XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX  gettext(u'Trade & Lays') XXXXXXXXX
        BB BBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX XXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXX XXXXXXXXXXXXX  gettext(u'Roteiro Curto (Shorts)') 
            XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX XXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXX XXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX  gettext(u'Roteiro Longo (YouTube)') 
            XXXXXXXXX
        XXXXXX
        BBBBB
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXX X XXXXXX XXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
        
        XXXX XXXX XXXXXXXX XXXXX XXXXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX  gettext(u'OVER/UNDER PROBABILITIES & TOP PICKS') 
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXX XX XXXXXX XXXXXXXXXX XXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXX XXX  gettext(u'Gols')  XXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Odd Justa') X FFFFFFFFXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBXXXXBBBBBXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXX
                    
                    XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXX XXX  gettext(u'Gols')  XXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Odd Justa') X FFFFFFFFXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBXXXXBBBBBXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXX
                    
                    XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXX XXX  gettext(u'Gols')  XXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Odd Justa') X FFFFFFFFXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXX
                    
                    XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXX XXX  gettext(u'Gols')  XXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Odd Justa') X FFFFFFFFXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXX

                    XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXX XXX  gettext(u'Gols')  XXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Odd Justa') X FFFFFFFFXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX

                XXXX XXXXXX XX XXXXXXXXX X XXXX XXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX
                    XXXX XXXX XXXX XXXXXX XXX
                    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXX XXXXXXXX XXXXXX XXXXXXX XXXXX XX XXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX
                        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX  gettext(u'Ambas Equipes Marcam (BTTS)') XXXXXX
                        XXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX gettext(u'Sim')  XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXFFFFFFFFXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX gettext(u'Não')  XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXFFFFFFFFXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX

                    XXXX XX XXXXXXXXXXX XXX
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXX XXXXXXX XXX XXXXX XXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXX XXXXXXX XXXXX XX XXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XX XXX XXXXXXXXXXX
                        
                        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXX  gettext(u'Gols') XXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXX XXXXXXXXXX XXXXXXXXX gettext(u'Recomendado') XXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Linha Principal (2.5)') XXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB B BBXXXX XXXBBBBXXXXX XXXBBBBBXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            
            XXXX XXXXX XX XXXX XXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXX gettext(u'Vencer a Partida') XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXX XXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXX gettext(u'Chance Dupla') XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXX  gettext(u'Seguro') XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Gol no 1º Tempo (HT)') XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXX gettext(u'Probabilidade') XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Marcar Primeiro') XXXXXX
                    XXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX
                        XXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXFFFFFFFFFFXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                        XXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXFFFFFFFFFFXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXX XX XXXXXXXXXXXX XXXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXX
            
            XXXX XXXXXXX X XXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'Margens & Metades') XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFF  gettext(u'por 1 gol') XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFF  gettext(u'por 2 gols') XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFF  gettext(u'por 3+ gols') XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Empate (Com Gols)') XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Empate (0-0)') XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                
                XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Distribuição') XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Mais gols no 1º Tempo') XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Mais gols no 2º Tempo') XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX

            XXXX XXXXX XX XXXX X XXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Faixas & HT/FT') XXXXXX
                
                XXXX XXXXXXXXXXXXX XXXXX XXXXXX
                    XXXX XXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Faixa FT') XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'1 a 2 Gols') XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'2 a 3 Gols') XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Clean Sheet') XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX

                XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Intervalo / Fim de Jogo') XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBXXXXBBBBBXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBXXXXBBBBBXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBXXXXBBBBBXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX

        XXXXXX
    XXXXXX XXXX XXX XXX XXXX XXX

    XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX

        XXXX XXXXX XXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXX  gettext(u'Vencedor + Ambos Marcam') XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFF X  gettext(u'Sim') XXXXXXX
                    XXXXX XXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBXXXXBBBBBXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFF X  gettext(u'Não') XXXXXXX
                    XXXXX XXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBXXXXBBBBBXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Empate')  X  gettext(u'Sim') XXXXXXX
                    XXXXX XXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBXXXXBBBBBXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Empate')  X  gettext(u'Não') XXXXXXX
                    XXXXX XXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBXXXXBBBBBXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFF X  gettext(u'Sim') XXXXXXX
                    XXXXX XXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBXXXXBBBBBXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFF X  gettext(u'Não') XXXXXXX
                    XXXXX XXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBXXXXBBBBBXXXXXXXXXX
                XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX  gettext(u'Chance Dupla + Faixa de Gols') XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX  gettext(u'Gols') XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX  gettext(u'Gols') XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX  gettext(u'Gols') XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX  gettext(u'Gols') XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX  gettext(u'Gols') XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX  gettext(u'Gols') XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXX  gettext(u'Handicap Asiático & Europeu') XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFF XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFF XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFF XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFF XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFF XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFF XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX  gettext(u'Empate Anula Aposta (Draw No Bet)') XXXXXX
                XXXX XXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXFFFFFFFFFFXXXXXXX
                        XXXXX XXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBXXXXBBBBBXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXFFFFFFFFFFXXXXXXX
                        XXXXX XXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBXXXXBBBBBXXXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX




        XXXX XX XXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX  gettext(u'MATCH ANALYSIS') XXXXXX
            XXXXXXX
        XXXXXX

    XXXXXX XXXX XXX XXX XXXXXXXXX XXX

    XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX

        XXXX XXXXXXXXXXXX XX XXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXX XXXXXXXXXXXXX  gettext(u'ELITE CORNERS PROJECTION') 
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXX XX XXXXXX X XXXX XXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXX
                        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXFFFFFFFFFF  gettext(u'Avg') XXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXX XXXXXXX
                            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX
                            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX
                        XXXXXX
                    XXXXXX

                    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXX
                        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXFFFFFFFFFF  gettext(u'Avg') XXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXX XXXXXXX
                            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX
                            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX
                        XXXXXX
                    XXXXXX
                    
                    XXXX XXXX X XXXX XXXXXXXXXXXXX XXX
                    XXXX XXXXXXXXXXXXX XXXXX XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Base do Jogo') XXXXXX
                            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Best Pick') XXXXXX
                            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX

                XXXX XXXXXX XX XXXXXX XX XXXXXXXXXXXXX XXXX XXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX  gettext(u'Probabilidades Over') XXXXXX
                    
                    XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBXXXXBBBBBXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBXXXXBBBBBXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBXXXXBBBBBXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            
            XXXX XXXXX XX XXXXX XXXXXX X XXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX  gettext(u'Match Winner (Cantos)') XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFF  gettext(u'Mais Escanteios') XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Empate') XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFF  gettext(u'Mais Escanteios') XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX  gettext(u'Handicap Asiático') XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFF XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFF XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX

            XXXX XXXXXXX XX XXXXXXXX XXXXXXXX XXX
            XXXX XXXXXXXXXXX XXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXX XXXXX XXXXXXXXXXXX XXX XXXXX XXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX  gettext(u'Analyst Insight: How to Profit') XXXXXX
                XX XXXXXXXXXXXXXX XX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
                    BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    BB BBBBBBBBBB BB BB
                         gettext(u'This game has a <strong>Base of %(base)s corners</strong>, indicating high offensive volume. With an Over 8.5 prob. at %(prob)s%%, the scenario is ideal for seeking "Over 8.5 or 9.5" corner markets.') 
                        SSSS SSSS SSS S SSSSSSSSSSSS SS SSSSSSSS SSSSSSSSSSSSSSSSS SSSSSSSSSS SSSS SSSSSSSSS SSSSSSS SSSS SS SSSS SSS SSSSS SS SSSSSSSSSSS SSS SSSSSSSS SS SSSSS SSS SSSSSSS SSSSS SSS SS SSSS SSSSSS SSSSSSSS
                        
                    BBBB BBBBBBBBBB BB B
                         gettext(u'The base of %(base)s suggests moderate volume. The best strategy here is to look for safety markets like "Over 7.5" or wait for "Live" for better odds.') 
                        SSS SSSS SS SSSSSSSS SSSSSSSS SSSSSSSS SSSSSSS SSS SSSS SSSSSSSS SSSS SS SS SSSS SSS SSSSSS SSSSSSS SSSS SSSSS SSSS SS SSSS SSS SSSSSS SSS SSSSSS SSSSS
                        
                    BBBB
                         gettext(u'Game with a tendency for low lateral volume (Base %(base)s). Be cautious with Over bets; the "Under" market or specific corners by time may be more profitable.') 
                        SSSS SSSS S SSSSSSSS SSS SSS SSSSSSS SSSSSS SSSSS SSSSSSSSSS SS SSSSSSSS SSSS SSSS SSSSS SSS SSSSSSS SSSSSS SS SSSSSSSS SSSSSSS SS SSSS SSS SS SSSS SSSSSSSSSSS
                        
                    BBBBB
                    BBBBBBB
                XXXX
            XXXXXX

        XXXXXX
    XXXXXX XXXX XXX XXX XXXXXXXXXX XXX

    XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX

        XXXX XXXXXXXXXXXX XX XXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX  gettext(u'ELITE DISCIPLINE PROJECTION') 
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXX XX XXXXXX XXXXXXXXXXXXX XXX
                    XXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXX
                            XXXX XXXXXXXXXXXXX XXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFXXXXXXX
                                XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Fouls') XXXXXXXXXXXXX
                            XXXXXX
                            XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXX XXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFXXXXXXX
                                XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Fouls') XXXXXXXXXXXXX
                            XXXXXX
                        XXXXXX

                        XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXX XXXXX XXXXXXX XXX XXXXXX XXXXXXXXX XXX XXX XXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Red Cards Avg:') XXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'per game') XXXXXXX
                        XXXXXX
                    XXXXXX

                    XXXX XXXXXX XX XXXXXX XXXX XX XXXXXXX XXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX  gettext(u'Probabilidades Over Cartões') XXXXXX
                        
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBXXXXBBBBBXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBXXXXBBBBBXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX

                XXXX XXXXX XX XXXXX XXXXXX X XXXXXXXX XXX
                XXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX  gettext(u'Match Winner (Cartões)') XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFF  gettext(u'Mais Cartões') XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Empate') XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFF  gettext(u'Mais Cartões') XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX  gettext(u'Handicap Asiático') XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFF XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFF XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX

                BBBB
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXX
                    XX XXXXXXXXXXXX XXXXX gettext(u'Insufficient disciplinary data') XXXX
                XXXXXX
                BBBBB

                XXXX XXXXXXX XX XXXXXXXX XXXXXXXX XXX
                XXXX XXXXXXXXXXX XXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXXX XXX XXXXX XXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX  gettext(u'Disciplinary Tip') XXXXXX
                    XX XXXXXXXXXXXXXX XX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
                        BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                        BB BBBBBBBBBBB BB BB
                             gettext(u'With an average of <strong>%(fouls)s fouls</strong>, we expect a tense game with many stops. The chance of cards (currently %(cards)s yellows/game) is high.') 
                            SSSS SS SSSSSSS SS SSSSSSSSSSSSSSSSS SSSSSSSSSSSSSSS SS SSSSSS S SSSSS SSSS SSSS SSSS SSSSSS SSS SSSSSS SS SSSSS SSSSSSSSSS SSSSSSSSS SSSSSSSSSSSSS SS SSSSS
                            
                        BBBB
                             gettext(u'Game with a tendency to be more fluid (only %(fouls)s fouls on average). The "Under Cards" or "Less than 4.5" market could be a good choice if the referee is not strict.') 
                            SSSS SSSS S SSSSSSSS SS SS SSSS SSSSS SSSSS SSSSSSSSS SSSSS SS SSSSSSSSS SSS SSSSSS SSSSSS SS SSSSS SSSS SSSS SSSSSS SSSSS SS S SSSS SSSSSS SS SSS SSSSSSS SS SSS SSSSSSS
                            
                        BBBBB
                        BBBBBBB
                    XXXX
                XXXXXX

            XXXXXX
        XXXXXX
    XXXXXX XXXX XXX XXX XXXXXXX XXX

    XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX

        XXXX XXXXXXXXXX XX XXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX  gettext(u'ELITE SHOTS & ATTACK PROJECTION') 
            XXXXXX
            
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXX XX XXX XX XXX XXXXXXXXXX XXX
                    XXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX  gettext(u'Shot Accuracy (Target)') XXXXXX
                            
                            XXXX XXX XX XXX XXX
                            XXXX XXXXXXXXXXXXXX XXXXXX
                                XXXX XXXXXXXXXXXXXXX XXXXXXFFFFFFFFFFXXXXXX
                                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                                XXXXXX
                            XXXXXX
                            
                            XXXX XXXXXXXXXXXXXX XXXXXX
                                XXXX XXXXXXXXXXXXXXX XXXXXXFFFFFFFFFFXXXXXX
                                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                                XXXXXX
                            XXXXXX
                        XXXXXX

                        XXXX XXXXXXXXXXXXX XXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Shots per Goal')  XFFFFFFFFFFXXXXXXX
                                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXX
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Shots per Goal')  XFFFFFFFFFFXXXXXXX
                                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX

                    XXXX XXXXXX XX XXXXXX XXXX XX XXXXXX XXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX  gettext(u'Total de Chutes (Over)') XXXXXX
                        
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBXXXXBBBBBXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBXXXXBBBBBXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXXXXX

                        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX  gettext(u'Chutes no Alvo') XXXXXX
                        
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX  gettext(u'Alvo') XXXXXXXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBXXXXBBBBBXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX  gettext(u'Alvo') XXXXXXXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBXXXXBBBBBXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX

                XXXX XXXXX XX XXXXX XXXXXX X XXXXXX XXXXXXXXXXX XXX
                XXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXXXXX  gettext(u'Match Winner (Chutes)') XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFF  gettext(u'Mais Chutes') XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFF  gettext(u'Mais Chutes') XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXX  gettext(u'Match Winner (No Alvo)') XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFF  gettext(u'Mais no Alvo') XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFF  gettext(u'Mais no Alvo') XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXXX  gettext(u'Linhas Individuais') XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFF XXXX XXXX  gettext(u'Chutes') XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFF XXXX XXX  gettext(u'no Alvo') XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXFFFFFFFFFF XXXX XXXX  gettext(u'Chutes') XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXFFFFFFFFFF XXXX XXX  gettext(u'no Alvo') XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX

                BBBB
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXX
                    XX XXXXXXXXXXXX XXXXX gettext(u'Shot statistics unavailable') XXXX
                XXXXXX
                BBBBB

                XXXX XXXXXXX XX XXXXXXXX XXXXXXXX XXX
                XXXX XXXXXXXXXXX XXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXXX XXX XXXXX XXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX  gettext(u'Efficiency Guide') XXXXXX
                    XX XXXXXXXXXXXXXX XX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BB
                             gettext(u'Both teams have accuracy above 30%% on target. This is a very strong signal for the <strong>"Both Teams to Score: Yes"</strong> or "Over 1.5/2.5 Goals" market.') 
                            SSSS SSSSS SSSS SSSSSSSS SSSSS SSSS SS SSSSSSS SSSS SS S SSSS SSSSSS SSSSSS SSS SSS SSSSSSSSSSSSS SSSSS SS SSSSSS SSSSSSSSSSSSS SS SSSSS SSSSSSS SSSSSS SSSSSSS
                            
                        BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BB
                             gettext(u'Only one of the teams is being lethal in finishing. Consider betting on the "Team Goals" market for the one with higher accuracy.') 
                            SSSS SSS SS SSS SSSSS SS SSSSS SSSSSS SS SSSSSSSSSS SSSSSSSS SSSSSSS SS SSS SSSSS SSSSSS SSSSSS SSS SSS SSS SSSS SSSSSS SSSSSSSSS
                            
                        BBBB
                             gettext(u'Both teams are struggling with finishing (Accuracy below 30%%). Game with a tendency for few goals, ideal for analyzing the "Under" market.') 
                            SSSS SSSSS SSS SSSSSSSSSS SSSS SSSSSSSSS SSSSSSSSS SSSSS SSSSSS SSSS SSSS S SSSSSSSS SSS SSS SSSSSS SSSSS SSS SSSSSSSSS SSS SSSSSSS SSSSSSS
                            
                        BBBBB
                    XXXX
                XXXXXX

            XXXXXX
        XXXXXX
    XXXXXX XXXX XXX XXX XXXXXX XXX

    XXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXX X XXXX XXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXX XXXXX XXX XXXX XXX
        XXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
                XX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX  gettext(u'Smart Lay Bets (Exchange)') 
            XXXXXX
            XX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX
                 gettext(u'Betting <strong>AGAINST</strong> these outcomes has a high statistical probability of success.') 
                SSSSSSS SSSSSSSSSSSSSSSSSSSSSSSS SSSSS SSSSSSSS SSS S SSSS SSSSSSSSSSS SSSSSSSSSSS SS SSSSSSSS
                
            XXXX
            
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX X XXXX XXXXXXXXXX XXXXXXXX
                    XXXXXXX
                        XXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
                            XXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Placar') XXXXX
                            XXX XXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Success') XXXXX
                            XXX XXXXXXXXXXXXXXXXXX XXXXXX gettext(u'FAIR ODD') XXXXX
                            XXX XXXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXX XXXXXXXX gettext(u'Exchange') XXXXX
                        XXXXX
                    XXXXXXXX
                    XXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBBBB
                        BBB BBB BB BBBBBBBBBBBBBBBBBBBBBBB
                        XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXX XXX XXXXXXXX XXX XXX XXXX XXXXXX XXXXXXXXXXX XXX XXXX XXXXXXX
                            XXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXX XXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXX X X XXXX XXXXXXXXX XXX XXX XXXXXXXXXXXXX
                                    XXXXX
                                        XXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                        XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX
                                    XXXXXX
                                XXXXXX
                            XXXXX
                            XXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXX XXXXXX XXXXXXX XXX XXXXX XXXXXXXXX XXX XXX XXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXX XXX XXXXX XXXXXXXXXXX XXXXX X X XXX XXXXXXXXX XXX XXX XXXXXXXX
                                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXX
                                XXXXXX
                            XXXXX
                            XXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXX XXX XXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXFFFFFFFFFFFFFXXXXXXX
                                XXXXXX
                            XXXXX
                            XXX XXXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXX XXXXX XXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXX XXXX XX XXXXXX XXXXX XXXXXXXXXXX X XXX XXXX XXXXXXXXX XXX XXX XXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXX gettext(u'LAY') XXXXXX
                                XXXXXX
                            XXXXX
                        XXXXX
                        BBBBBB
                    BBBB
                        XXXX
                            XXX XXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX
                                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXX
                                    XX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXX gettext(u'No high-probability Lay bets found.') XXXX
                                XXXXXX
                            XXXXX
                        XXXXX
                    BBBBB
                    XXXXXXXX
                XXXXXXXX
            XXXXXX
            
            XXXXXXX
                XXXXXXXXXXXXXX X
                    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXX XXX XXXXXXXX XXX XXX XXXX XXXXX XXXXXXXXXXX
                    XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXXXXXXXXX X XXXX XXXX XXXXXXXXXXXXXXXX
                    XXXXXXXX XXX
                    XXXXXXXXX XXXXXXXXX
                X
            XXXXXXXX
        XXXXXX
    XXXXXX XXXX XXX XXX XXXX XXX

    BBBBB

XXXXXX


BBBBBBBB

BBBBB BBBBBBBB
XXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
        XX XXXXXX XXXXXX XX XXXXX XX XXXXXX X XXXXXX XXXXX XX XXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX
        
        XX XXXXX X XXXXX XXXXXXX
        XX XXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X XXXX X
            XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
        
        XX XXXXXX X XXXXXXXX XXXXXXXXXXXXXX
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
        XX XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
    X

    XXXXXXXX XXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXX XXX XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X XXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX
        
        XX XXXXXXX XXX XXXXXX XXX XXXX XXXXX
        XXXXX XXXXXXXX X XXXXXXXXXXFFFFFFFFFFFXX XXXX
        
        XX XXXXXXXXXXXXXXXXXX X
            XXXXX XXXXXXXX X XXXXXXXXXXFFFFFFFFFFFXX XXX XX XX
            XXXXX XXXXXX X XXXXXXXXXXFFFFFFFFFFFXX XXX XX XX
            XXXXX XXXXXX X XXXXXXXXXXFFFFFFFFFFFXX XXX XX XX
            XXXXX XXXXXXX X XXXXXXXXXXFFFFFFFFFFFXX XXX XX XX
            XXXXX XXXXXXX X XXXXXXXXXXFFFFFFFFFFFXX XXX XX XX
            
            XXXXXXXX XXXXXXXXXXXX X
                XXXXX XXXXX X X
                    X XX XXXXXXXXX XX XXXXXXXX XX
                    X XX XXXXXXX XX XXXXXX XX
                    X XX XXXXXXXX XX XXXXXXX X
                XX
                XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                XXXXXXXXXXXXXXXXX XX XX X
                    XXXXX XXXXX X XXX X XXXX
                    XXXXX XXXX X XXXXX X X X XXXX X XXXXXX X XXX X XXX
                    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X XXXX X XXXX
                XXX
            X
            XXXXXXXXXXXXX
        X
    XXX

    BB BBBBBBBBBBBBBBB
    XXXXX XXXXXXXXXXXX X X
        X gettext(u'Analisando estatísticas do Statsfut...') XX
        X gettext(u'Consultando a inteligência do DeepSeek v3...') XX
        X gettext(u'Estruturando o roteiro de alta conversão...') XX
        X gettext(u'Finalizando ganchos e palpites de valor...') X
    XX
    XXX XXXXXXXXXXXXXXXXXXX X XXXXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX X
        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXX XXXXXXX XXXX
        XXX XXXXXXX X XX
        XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX XX X
            XXXXXXX X XXXXXXXX X XX X XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXX
        
        XX XXXXXXXX XXXX XXX XXXX XXXXXX XX XXXX
        XXX XXXXXXXXX X XXXXXXX
        XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXX X
            XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
        X
        
        XX XXXXX XXXXXX XXXX XXX XXXXXXXX X XXXXXXX X X XXX
        XXXXX XXX X XBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXX
            XXXXXXXXXXX XXX XX X
                XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXX X
                    XXXXXX XXXXXXXXXXX
                X XXXX X
                    XXXXX XXX XXXXXXXX XXXXXXXX XXXXXXX XXXXX XXXX XXXXXXXXX XXXXXXXXXX X XX XXXXXX XXXXX XX XXXXX XXXXX XXXXXXXXX
                X
            XX
            XXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXX XXX XXXXXXXXXX X
                    XXXXXXXXXXXXXX X XXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X XXXX X
                    XXXXXXXXXXXXXX X X gettext(u'Erro') X X X XXXXXXXXXXXXX XX X gettext(u'Erro desconhecido') XXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X
            XX
            XXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXX X X gettext(u'Erro na requisição') X X X XXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX
    X

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X
        XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXX
        X
    X

    XXXXXXXX XXXXXXXXXXXXXXXXX X
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX XX X
                XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXX X XXXXXXXXXXXXXX
                XXXXXXXXXXXXX X XXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX  gettext(u'Copiado!') XX
                XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
                XXXXXXXXXXXXX XX X
                    XXXXXXXXXXXXX X XXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
                XX XXXXXX
            XX
            XXXXXXXXXX XX X
                XXXXXXXXXXX XX XXXXXXX X X XXXXX
            XXX
    X
    BBBBB
XXXXXXXXX

BB BBBBBBBBBBBBBBB
XXXX XXXXX XX XXXXXXX XX XXXXX XX XXX
XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Roteiro de Vídeo IA') XXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX gettext(u'Analisando histórico de confrontos...') XXXX
            XXXXXX
            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Fechar') XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX  gettext(u'Copiar Roteiro') 
            XXXXXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXX XX XXXXX XXX
    XXXX XXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX
BBBBB
BBBBBBBB
