BBBB BBBB
XXXX XXXXXXX XXXXXXX X XXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXX
     gettext(u'Current Streaks & Sequences') 
XXXXXX
XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX
    XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXX XXXXXX XXXX XXXXXXXXXXXX XXXXXXXXX
                     gettext(u'CURRENT SEQUENCES') 
                XXXXX
                XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Home') XXXXX
                XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Away') XXXXX
                XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Total') XXXXX
            XXXXX
        XXXXXXXX
        XXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX gettext(u'Consecutive wins') XXXXX
                XXX XXXXXXXBB BBBBBBBBBBBBBBBB BB BBBXXXXXXXXXXXXXXXXBBBBBXXXXXXX
                XXX XXXXXXXBB BBBBBBBBBBBBBBBB BB BBBXXXXXXXXXXXXXXXXBBBBBXXXXXXX
                XXX XXXXXXXBB BBBBBBBBBBBBBBBBB BB BBBXXXXXXXXXXXXXXXXBBBBBXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX gettext(u'Consecutive draws') XXXXX
                XXX XXXXXXXBB BBBBBBBBBBBBBBBBB BB BBBXXXXXXXXXXXXXXXXBBBBBXXXXXXX
                XXX XXXXXXXBB BBBBBBBBBBBBBBBBB BB BBBXXXXXXXXXXXXXXXXBBBBBXXXXXXX
                XXX XXXXXXXBB BBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXXXXXXXXXBBBBBXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX gettext(u'Consecutive defeats') XXXXX
                XXX XXXXXXXBB BBBBBBBBBBBBBBBBB BB BBBXXXXXXXXXXXXXXXBBBBBXXXXXXX
                XXX XXXXXXXBB BBBBBBBBBBBBBBBBB BB BBBXXXXXXXXXXXXXXXBBBBBXXXXXXX
                XXX XXXXXXXBB BBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXXXXXXXXBBBBBXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX

            XXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXX XXXXX XXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX gettext(u'No win') XXXXX
                XXX XXXXXXXBB BBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXXXXXXXXBBBBBXXXXXXX
                XXX XXXXXXXBB BBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXXXXXXXXBBBBBXXXXXXX
                XXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXXXXXXXXBBBBBXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX gettext(u'No draw') XXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX gettext(u'No defeat') XXXXX
                XXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXXXXXXXXXBBBBBXXXXXXX
                XXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXXXXXXXXXBBBBBXXXXXXX
                XXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXXXXXXXXXBBBBBXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX

            XXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXX XXXXX XXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX gettext(u'1 goal scored or more') XXXXX
                XXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXXXXXXXXXBBBBBXXXXXXX
                XXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXXXXXXXXXBBBBBXXXXXXX
                XXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXXXXXXXXXBBBBBXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX gettext(u'1 goal conceded or more') XXXXX
                XXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXXXXXXXXBBBBBXXXXXXX
                XXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXXXXXXXXBBBBBXXXXXXX
                XXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXXXXXXXXBBBBBXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX gettext(u'No goal scored') XXXXX
                XXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXXXXXXXXBBBBBXXXXXXX
                XXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXXXXXXXXBBBBBXXXXXXX
                XXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXXXXXXXXBBBBBXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX gettext(u'No goal conceded') XXXXX
                XXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXXXXXXXXXBBBBBXXXXXXX
                XXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXXXXXXXXXBBBBBXXXXXXX
                XXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXXXXXXXXXBBBBBXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX gettext(u'GF+GA over 2.5') XXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX gettext(u'GF+GA under 2.5') XXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXX XXXXX XXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXX gettext(u'Scored at least twice') XXXXX
                XXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXXXXXXXXXBBBBBXXXXXXX
                XXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXXXXXXXXXBBBBBXXXXXXX
                XXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBXXXXXXXXXXXXXXXXBBBBBXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
        XXXXXXXX
    XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXX
        XXXXXXX XXXXXXXXXXXXXX XXX XXXXX XXXXX XXXXXXXXXXX XXXXX XXXXXXXX XXX XXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXX
             gettext(u'Current Sequences table') 
        XXXXXXXXX
    XXXXXX
XXXXXX

XXXX XXXXXXXXXX XXXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXX XXXXXXXXXX XXXXXXXXXX gettext(u'Historical statistics') XXXXXX
XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXX
    XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXX XXXXX XXXXXXX
        XXXX XXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX
          gettext(u'(current season vs completed previous season)') 
    XXXXXX

    XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXX
                XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Season') XXXXX
                XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Pld') XXXXX
                XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Avg Pts') XXXXX
                XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Avg GF') XXXXX
                XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Avg GA') XXXXX
                XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'W') XXXXX
                XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'D') XXXXX
                XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'L') XXXXX
                XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'CS') XXXXX
                XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'FTS') XXXXX
            XXXXX
        XXXXXXXX
        XXXXXXX
            XXXX XXXXXXX XXX
            XXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXFFFFFFFFFFFFFXXXXX
                XXXXFFFFFFFFFFFFFXXXXX
                XXXXFFFFFFFFFFFFFXXXXX
                XXXXXXXXXX
                XXXXXXXXXX
                XXXXXXXXXX
                XXXXXXXXXX
                XXXXXXXXXX
            XXXXX

            XXXX XXXX XXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXX
                XXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXX
                XXXX XXXXXXXXXXX
                XXXXXXXXX
                XXXXFFFFFFFFFFFFFXXXXX
                XXXXFFFFFFFFFFFFFXXXXX
                XXXXFFFFFFFFFFFFFXXXXX
                XXXXXXXXXX
                XXXXXXXXXX
                XXXXXXXXXX
                XXXXXXXXXX
                XXXXXXXXXX
            XXXXX

            XXXX XXXX XXX
            XXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXX
                XXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXX
                XXXXXXXXX
                XXXXFFFFFFFFFFFFFXXXXX
                XXXXFFFFFFFFFFFFFXXXXX
                XXXXFFFFFFFFFFFFFXXXXX
                XXXXXXXXXX
                XXXXXXXXXX
                XXXXXXXXXX
                XXXXXXXXXX
                XXXXXXXXXX
            XXXXX
        XXXXXXXX
    XXXXXXXX
XXXXXX

XXXXXXX
    XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXXX
    X

    XXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXXX
    X

    XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXXXX
        XXXXXXXXXXXX XXXXX
    X

    XXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXX
    X

    XXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXX
    X

    XXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXX
    X
XXXXXXXX