BBBB BBBB BBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXX
        XXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXX gettext(u'Team') XXXXX
                XXXX gettext(u'Matches') XXXXX
                XXXXXXXXXX
                XXXXXXXXXX
                XXXXXXXXXX
                XXXXXXXXXX
                XXXX gettext(u'Goals') XXXXX
                XXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
        XXXXXXXX
        XXXXXXX
            BBB BBBBBBBB BB BBBB
            XXXX
                XXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXBBBBB
                        
                    XXXX
                XXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXX X XXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXXX
                XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXX X XXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXFFFFFFFFFFFFFXXXXX
            XXXXX
            BBBBBB
        XXXXXXXX
    XXXXXXXX
XXXXXX
