BBBB BBBB BBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXX
        XXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXX gettext(u'Team') XXXXX
                XXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXX gettext(u'Avg. min') XXXXX
                XXXXXXXXXXXXX
                XXXXXXXXXXXXXX
                XXXXXXXXXXXXXX
                XXXXXXXXXXXXXX
                XXXXXXXXXXXXXX
                XXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXX XXXXXXXX gettext(u'1st Half vs 2nd Half') XXXXX
            XXXXX
        XXXXXXXX
        XXXXXXX
            BBB BBBBBBBB BB BBBB
            XXXX
                XXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXBBBBB
                        
                    XXXX
                XXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                
                BB BBBBBB BB BBBBB
                    XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXX XXXXXXXXXFFFFFFFFFFFFFXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXX
                        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXFFFFFFFFFFFFFXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                            XXXXXX
                            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXFFFFFFFFFFFFFXXXXXXXX
                        XXXXXX
                    XXXXX
                BBBB BBBBBB BB BBBBB
                    XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXFFFFFFFFFFFFFXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXX
                        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXFFFFFFFFFFFFFXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                            XXXXXX
                            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXFFFFFFFFFFFFFXXXXXXXX
                        XXXXXX
                    XXXXX
                BBBB
                    XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXFFFFFFFFFFFFFXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXX
                        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXFFFFFFFFFFFFFXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                            XXXXXX
                            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXFFFFFFFFFFFFFXXXXXXXX
                        XXXXXX
                    XXXXX
                BBBBB
            XXXXX
            BBBBBB
        XXXXXXXX
    XXXXXXXX
XXXXXX
