
import os
import re

file_path = r'C:\Users\VGR\.gemini\antigravity\scratch\betstats_python\matches\templates\matches\team_detail.html'

with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

# 1. Remove CSS blocks
# Top block: <style>...</style> around lines 7-315
# We can regex replace <style>.*?</style> but there are multiple.
# The first one is big. The second one is small.
# We will identify them by content or just remove all <style> blocks and rely on the external file content I verified.
# BUT, I must ensure I don't delete styles I didn't extract.
# I extracted lines 7-315 and 1397-1427.

# Let's replace the first style block
content = re.sub(r'(?s)<style>\s*/\* SoccerStats Theme - Wide & Vivid \*/.*?</style>', 
                 r'<link rel="stylesheet" href="{% static \'matches/css/team_detail.css\' %}">', content, count=1)

# Replace the second style block (lines 1397-1427)
# It starts with .bg-success-light
content = re.sub(r'(?s)<style>\s*\.bg-success-light \{.*?</style>', '', content, count=1)

# 2. Remove JS block
# Starts with <script> document.addEventListener
content = re.sub(r'(?s)<script>\s*document\.addEventListener.*?</script>', 
                 r'<script src="{% static \'matches/js/team_detail.js\' %}"></script>', content, count=1)

# 3. Fix split tags
# Fix {{ ... }} split across lines
# Regex: {{ followed by anything not }} (non-greedy), then newline, then anything not }}, then }}
# We apply this iteratively until no changes

def fix_split_tags(text):
    pattern_var = r'(\{\{[^}]*?)\n\s*([^}]*?\}\})'
    pattern_block = r'(\{%\s*if[^%]*?)\n\s*([^%]*?%\})' # Only target IF tags for now to be safe, or ALL blocks?
    # The user issue was mostly IF and VAR tags.
    # Let's target ALL {% ... %} that are split inside the tag
    pattern_tag = r'(\{%\s*[^%]*?)\n\s*([^%]*?%\})'
    
    # Fix variables {{ ... }}
    while True:
        new_text = re.sub(pattern_var, r'\1 \2', text)
        if new_text == text:
            break
        text = new_text
        
    # Fix block tags {% ... %}
    while True:
        new_text = re.sub(pattern_tag, r'\1 \2', text)
        if new_text == text:
            break
        text = new_text
        
    return text

content = fix_split_tags(content)

# Remove multiple spaces inside tags generated by join
content = re.sub(r'(\{\{|\{%)\s+', r'\1 ', content)
content = re.sub(r'\s+(\}\}|%\})', r' \1', content)

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)

print("SUCCESS: Template refactored and tags fixed.")
