UPDATE betstats.matches_team SET name = 'Bahia', api_id = 'sofa_1955' WHERE name = 'Bahia';
UPDATE betstats.matches_team SET name = 'Botafogo', api_id = 'sofa_1958' WHERE name = 'Botafogo';
UPDATE betstats.matches_team SET name = 'Red Bull Bragantino', api_id = 'sofa_1999' WHERE name = 'Bragantino';
UPDATE betstats.matches_team SET name = 'Chapecoense', api_id = 'sofa_21845' WHERE name = 'Chapecoense';
UPDATE betstats.matches_team SET name = 'Corinthians', api_id = 'sofa_1957' WHERE name = 'Corinthians';
UPDATE betstats.matches_team SET name = 'Coritiba', api_id = 'sofa_1982' WHERE name = 'Coritiba';
UPDATE betstats.matches_team SET name = 'Coritiba', api_id = 'sofa_1982' WHERE name = 'Criciuma';
UPDATE betstats.matches_team SET name = 'Cruzeiro', api_id = 'sofa_1954' WHERE name = 'Cruzeiro';
UPDATE betstats.matches_team SET name = 'Fluminense', api_id = 'sofa_1961' WHERE name = 'Figueirense';
UPDATE betstats.matches_team SET name = 'Flamengo', api_id = 'sofa_5981' WHERE name = 'Flamengo';
UPDATE betstats.matches_team SET name = 'Fluminense', api_id = 'sofa_1961' WHERE name = 'Fluminense';
UPDATE betstats.matches_team SET name = 'Grêmio', api_id = 'sofa_5926' WHERE name = 'Gremio';
UPDATE betstats.matches_team SET name = 'Internacional', api_id = 'sofa_1966' WHERE name = 'Internacional';
UPDATE betstats.matches_team SET name = 'Mirassol', api_id = 'sofa_21982' WHERE name = 'Mirassol';
UPDATE betstats.matches_team SET name = 'Palmeiras', api_id = 'sofa_1963' WHERE name = 'Palmeiras';
UPDATE betstats.matches_team SET name = 'Remo', api_id = 'sofa_2012' WHERE name = 'Remo';
UPDATE betstats.matches_team SET name = 'Santos', api_id = 'sofa_1968' WHERE name = 'Santos';
UPDATE betstats.matches_team SET name = 'São Paulo', api_id = 'sofa_1981' WHERE name = 'Sao Paulo';
UPDATE betstats.matches_team SET name = 'Vasco da Gama', api_id = 'sofa_1974' WHERE name = 'Vasco';
UPDATE betstats.matches_team SET name = 'Vitória', api_id = 'sofa_1962' WHERE name = 'Vitoria';