UPDATE betstats.matches_team SET name = 'BSC Young Boys', api_id = 'sofa_2445' WHERE name = 'Young Boys' AND league_id = 42;
UPDATE betstats.matches_team SET name = 'BSC Young Boys', api_id = 'sofa_2445' WHERE name = 'BSC Young Boys' AND league_id = 42;
UPDATE betstats.matches_team SET name = 'Basel', api_id = 'sofa_2501' WHERE name = 'Basel' AND league_id = 42;
UPDATE betstats.matches_team SET name = 'FC Lugano', api_id = 'sofa_2443' WHERE name = 'Lugano' AND league_id = 42;
UPDATE betstats.matches_team SET name = 'FC Lugano', api_id = 'sofa_2443' WHERE name = 'FC Lugano' AND league_id = 42;
UPDATE betstats.matches_team SET name = 'FC Luzern', api_id = 'sofa_2453' WHERE name = 'Luzern' AND league_id = 42;
UPDATE betstats.matches_team SET name = 'FC Luzern', api_id = 'sofa_2453' WHERE name = 'FC Luzern' AND league_id = 42;
UPDATE betstats.matches_team SET name = 'FC Sion', api_id = 'sofa_2452' WHERE name = 'Sion' AND league_id = 42;
UPDATE betstats.matches_team SET name = 'FC Sion', api_id = 'sofa_2452' WHERE name = 'FC Sion' AND league_id = 42;
UPDATE betstats.matches_team SET name = 'FC St. Gallen 1879', api_id = 'sofa_2442' WHERE name = 'St. Gallen' AND league_id = 42;
UPDATE betstats.matches_team SET name = 'FC St. Gallen 1879', api_id = 'sofa_2442' WHERE name = 'FC St. Gallen 1879' AND league_id = 42;
UPDATE betstats.matches_team SET name = 'FC Zürich', api_id = 'sofa_2450' WHERE name = 'Zurich' AND league_id = 42;
UPDATE betstats.matches_team SET name = 'FC Zürich', api_id = 'sofa_2450' WHERE name = 'FC Zürich' AND league_id = 42;
UPDATE betstats.matches_team SET name = 'Servette FC', api_id = 'sofa_2448' WHERE name = 'Servette' AND league_id = 42;
UPDATE betstats.matches_team SET name = 'Servette FC', api_id = 'sofa_2448' WHERE name = 'Servette FC' AND league_id = 42;
UPDATE betstats.matches_team SET name = 'FC Winterthur', api_id = 'sofa_2458' WHERE name = 'Winterthur' AND league_id = 42;
UPDATE betstats.matches_team SET name = 'FC Winterthur', api_id = 'sofa_2458' WHERE name = 'FC Winterthur' AND league_id = 42;
UPDATE betstats.matches_team SET name = 'Grasshopper Club Zürich', api_id = 'sofa_2449' WHERE name = 'Grasshoppers' AND league_id = 42;
UPDATE betstats.matches_team SET name = 'Grasshopper Club Zürich', api_id = 'sofa_2449' WHERE name = 'Grasshopper Club Zürich' AND league_id = 42;
UPDATE betstats.matches_team SET name = 'FC Lausanne-Sport', api_id = 'sofa_2446' WHERE name = 'Lausanne' AND league_id = 42;
UPDATE betstats.matches_team SET name = 'FC Lausanne-Sport', api_id = 'sofa_2446' WHERE name = 'FC Lausanne-Sport' AND league_id = 42;
UPDATE betstats.matches_team SET name = 'FC Thun', api_id = 'sofa_2454' WHERE name = 'Thun' AND league_id = 42;
UPDATE betstats.matches_team SET name = 'FC Thun', api_id = 'sofa_2454' WHERE name = 'FC Thun' AND league_id = 42;