BBBB BBBB
BBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXX
                XXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXFFFFFFFFFFFFFFFFXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXX gettext(u'Total Odd') XXXXXX
                XXXXXX
                XXXXX
                    XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXX gettext(u'Accuracy') XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXX XXXXXX
            XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
                BBB BBB BB BBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX BB BBB BBBBBBBBBBBBXXXXXXXXXXXXXBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                        BB BBBBBBBBBB BB BBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXX
                            XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XXXXXX
                        BBBB BBBBBBBBBB BB BBBBB
                        XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXX
                            XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XXXXXX
                        BBBB
                        XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXX
                            XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXXXXX
                        BBBBB
                        XXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX
                            BB BBBBBBBBBB BB BBBBBBB
                                XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX X  X XXXXXXXXXXXX
                            BBBB BBBBBBBBBB BB BBBBB
                                XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX X  X XXXXXXXXXX
                            BBBB
                                XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXFFFFFFFFF FFFFXXXXXXX
                            BBBBB
                        XXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX
                            BB BBBBBBBBBB BB BBBBBBB
                            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXX
                            BBBB BBBBBBBBBB BB BBBBB
                            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXX
                            BBBB
                            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXX
                            BBBBBXX
                            FFFFFFFFFFFFFFFF
                        XXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXX
                            XXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXX XXXXX XXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXX XXXX XXX XXXXX XXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXX
                             gettext(u'Probability') X X
                        XXXXXXX
                    XXXXXX
                XXXXXX
                BBBBBB
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                BB BBBBBBBBBBBBB B B
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXX XXXXX XXXX XXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX  gettext(u'match(es) pending') XXXXXXX
                XXXXXX
                BBBB
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXX gettext(u'All matches finished') XXXXXXX
                XXXXXX
                BBBBB
                BBBBBBB
                XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFFFFXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
