BBBBBBB BBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBB gettext(u'Login')  X XXXXXXXXBBBBBBBB
BBBBB BBBBBBBBBBBBBBBB gettext(u'Login to access StatsFut Premium analytics and advanced football statistics.') BBBBBBBB

BBBBB BBBBBB
XXX XXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX gettext(u'Login') XXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXX
            
            XXXX XXXXXX XXXX XXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
                XXXXXX
                XXX XXXXXXXXX XXXXXXXXXX XXXXXX gettext(u'Welcome Back') XXXXX
                XX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX gettext(u'Sign in to access your premium stats') XXXX
            XXXXXX

            XXXX XXXXXXXX XXX
            BB BBBBBBBB
            BBB BBBBBBB BB BBBBBBBB
            XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXBB BBBBBBBBBBBB BB BBBBBBBBBXXXXXXXXXBBBB BBBBBBBBBBBB BB BBBBBBBXXXXXXXXXBBBBXXXXXXXXXXBBBBBX XXXXXX XXXXXX BB BBBBBBBBBBBB BB BBBBBBBBBXXXXXXXBBBB BBBBBBBBBBBB BB BBBBBBBXXXXXXXBBBBXXXXXXXBBBBBXXX
                
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            BBBBBB
            BBBBB

            XXXX XXXX XXXXXX XXX
            BB BBBBBBBBBBB
            XXXX XXXXXXXXXXXX XXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX
                XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                 gettext(u'Invalid username or password. Please try again.') 
            XXXXXX
            BBBBB

            XXXX XXXXX XXXX XXX
            XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                BBBBBBBBBB
                
                XXXX XXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                        XX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX gettext(u'Username') 
                    XXXXXXXX
                    
                XXXXXX
                
                XXXX XXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                        XX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX gettext(u'Password') 
                    XXXXXXXX
                    
                XXXXXX

                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXX XXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXX XXXX XXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Sign In') 
                XXXXXXXXX
            XXXXXXX

            XXXX XXXXXXX XXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX gettext(u'OR') XXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX

            XXXX XXXXXXXX XXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX gettext(u"Don't have an account?") XXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX gettext(u'Create Account') 
                XXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXXXXXXX X X X XXXXXX XXXXXXXX XXXX XXXX XXXXXX
    X
    XXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXXX XXXX XXXX XXXXXX
    X
    XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXXXXXXXX
    X
XXXXXXXX

XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        
        XX XXXXXXXXXX XX XXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
                XX XXXXXXX XXXXXX XX XXXXXXX XXXXXXXXXXXX XXXX XXXXXX XX XXXXXX
                XXXXXXXXXXXXXXXXX X XXXXX
                XXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXX gettext(u'Signing in...') XX
            XXX
        X
    XXX
XXXXXXXXX
BBBBBBBB
