BBBBBBB BBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBB gettext(u'Upgrade to Premium')  X XXXXXXXXBBBBBBBB
BBBBB BBBBBBBBBBBBBBBB gettext(u'Upgrade to StatsFut Premium for exclusive advanced football analytics, corner stats, card analysis and AI predictions.') BBBBBBBB

BBBBB BBBBBB
XXX XXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Upgrade to Premium') XXXXX
BBBBBBBB

BBBBB BBBBBBB

XXXX XXXX XXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXX
    XXXXXX
    XXX XXXXXXXXXXXXXXXXX XXXXXX gettext(u'Unlock the Full Power of StatsFut') XXXXX
    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX gettext(u'Get access to advanced analytics used by professional bettors and analysts. Corner stats, card trends, AI predictions and much more.') XXXX
XXXXXX

XXXX XXXXXXX XXXXX XXXXXX XXX
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX
    XXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Monthly') XXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXX
    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
         gettext(u'Quarterly')  
        XXXXX XXXXXXXXXXXX XXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX
    XXXXXXX
XXXXXX

XXXX XXXXXXX XXXXX XXX
XXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX

    XXXX XXXXXXX XXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXX
                XXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXX XXXXXXXXXX XXXXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX gettext(u'Popular') 
                XXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXX
                XXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'month') XXXXXXX
            XXXXXX
            XX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXX gettext(u'Perfect to start using our AI predictions') XXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX
                XXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Advanced Corner Analysis') XXXXXXX
                XXXXX
                XXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Card & Foul Trends') XXXXXXX
                XXXXX
                XXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Shot Analysis & xG') XXXXXXX
                XXXXX
                XXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXX XXXXXXX gettext(u'AI Smart Predictions (Scanner)') XXXXXXX
                XXXXX
                XXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Deep H2H Analytics') XXXXXXX
                XXXXX
                XXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXX gettext(u'Ready Strategies (Expert Tickets)') XXXXXXX
                XXXXX
            XXXXX
            BB BBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXX XXXX XXXXXXX
                        XX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX gettext(u'PIX ou Cartão (Brasil)') 
                    XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXX
                        XX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX gettext(u'International Card') 
                    XXXX
                XXXXXX
            BBBB
                XX XXXXXXBBB BBBBBBBBBBBBBBBXXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX gettext(u'Subscribe Popular') 
                XXXX
            BBBBB
        XXXXXX
    XXXXXX

    XXXX XXX X XXXX XXXXX XXXX XXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXX XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXX XXXXX XXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX gettext(u'BEST VALUE / VIP') 
                XXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXX XXXXXX
                XXXXX XXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX gettext(u'VIP Full Access') 
                XXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXX
                XXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX gettext(u'month') XXXXXXX
            XXXXXX
            XX XXXXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Everything unlocked') XXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX
                XXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX gettext(u'Everything in Popular') XXXXXXX
                XXXXX
                XXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX gettext(u'Ready Strategies (Expert Tickets)') XXXXXXX
                XXXXX
                XXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Doubles & Triples (80%%+ win rate)') XXXXXXX
                XXXXX
                XXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Priority Support (WhatsApp)') XXXXXXX
                XXXXX
                XXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Early access to new features') XXXXXXX
                XXXXX
            XXXXX
            BB BBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXX XXXX XXXXX XXXXXXXXXXX X XXX XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX gettext(u'PIX ou Cartão (Brasil)') 
                    XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXX
                        XX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX gettext(u'International Card') 
                    XXXX
                XXXXXX
            BBBB
                XX XXXXXXBBB BBBBBBBBBBBBBBBXXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXX XXXXXXXXXXX XXX XXXX XXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX gettext(u'Subscribe VIP') 
                XXXX
            BBBBB
        XXXXXX
    XXXXXX
XXXXXX

XXXX XXX XXXXXXX XXX
XXXX XXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX gettext(u'Frequently Asked Questions') XXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'What payment methods do you accept?') 
                XXXXXXXXX
            XXXXX
            XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX gettext(u'We accept PIX, credit cards, and boleto bancário. International users can pay via credit card.') XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Can I cancel anytime?') 
                XXXXXXXXX
            XXXXX
            XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX gettext(u"Yes! You can cancel your subscription at any time. You'll keep access until the end of your billing period.") XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'How often is the data updated?') 
                XXXXXXXXX
            XXXXX
            XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX gettext(u'All statistics are updated automatically every day. Live scores update in real-time during matches.') XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXXXXX
    XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXXXX XXXX XXX XXXXX
    X
    XXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXX XXXXXXXXXX
    X
    XX XXXXXX XXXXX XXX XXX XXXXXXXXX XXXXXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
    X
    XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    X
    XXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXX XXXX XXXXX
    X
XXXXXXXX

XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XX XXXXXXXXXXXXXXXX X
                XX XXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX X XXX XXXX
                XXXXXXXXXXXXXXXXXXXXXXXXX X XX gettext(u'3 months') XX
                XXXXXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXXX XXXXXX XXXX XXXXXXXXXXXXXXXXXX  gettext(u'Equivale a R$ 23/mês') XX
                
                XXXXXXXXXXXXXXXXXXXX X XXX XXXXX
                XXXXXXXXXXXXXXXXXXXXX X XX gettext(u'3 months') XX
                XXXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXXX XXXXXX XXXX XXXXXXXXXXXXXXXXXX  gettext(u'Equivale a R$ 39/mês') XX

                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                XX XXXXXXXXX XXXXX XX XXXXXX
                XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                XX XXXXXXXXX XXXXX XX XXXXXX
                XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X XXXX X
                XX XXXXXX XXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX X XXX XXXX
                XXXXXXXXXXXXXXXXXXXXXXXXX X XX gettext(u'month') XX
                XXXXXXXXXXXXXXXXXXXXXXX X X gettext(u'Perfect to start using our AI predictions') XX

                XXXXXXXXXXXXXXXXXXXX X XXX XXXX
                XXXXXXXXXXXXXXXXXXXXX X XX gettext(u'month') XX
                XXXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX  gettext(u'Everything unlocked') XX

                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                XX XXXXXXXXX XXXXX XX XXXXXX
                XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                XX XXXXXXXXX XXXXX XX XXXXXX
                XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        XXX
    XXX
XXXXXXXXX
BBBBBBBB
