BBBBBBB BBBBBBBBBBB
BBBB BBBBBB BBBB

BBBBB BBBBB gettext(u'Create Account')  X XXXXXXXXBBBBBBBB
BBBBB BBBBBBBBBBBBBBBB gettext(u'Create your StatsFut account to access premium football analytics and advanced statistics.') BBBBBBBB

BBBBB BBBBBB
XXX XXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX gettext(u'Create Account') XXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXX
            
            XXXX XXXXXX XXXX XXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
                XXXXXX
                XXX XXXXXXXXX XXXXXXXXXX XXXXXX gettext(u'Join StatsFut') XXXXX
                XX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX gettext(u'Create your account and unlock advanced analytics') XXXX
            XXXXXX

            XXXX XXXXXXXX XXX
            BB BBBBBBBB
            BBB BBBBBBB BB BBBBBBBB
            XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX
                
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            BBBBBB
            BBBBB

            XXXX XXXX XXXXXX XXX
            BB BBBBBBBBBBB
            XXXX XXXXXXXXXXXX XXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX
                XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXX XXXXXXXXXXX XXXXXX
                BBB BBBBB BB BBBB
                    BBB BBBBB BB BBBBBBBBBBBB
                    XXXXXXXXX
                    BBBBBB
                BBBBBB
                BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
                    XXXXXXXXX
                BBBBBB
                XXXXX
            XXXXXX
            BBBBB

            XXXX XXXXXXXX XXXX XXX
            XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                BBBBBBBBBB
                
                XXXX XXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                        XX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX gettext(u'Username') 
                    XXXXXXXX
                    
                    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Letters, digits and @/./+/-/_ only.') XXXXXX
                XXXXXX

                XXXX XXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                        XX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX gettext(u'Email') 
                    XXXXXXXX
                    
                XXXXXX
                
                XXXX XXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                        XX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX gettext(u'Password') 
                    XXXXXXXX
                    
                    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'At least 8 characters.') XXXXXX
                XXXXXX

                XXXX XXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                        XX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX gettext(u'Confirm Password') 
                    XXXXXXXX
                    
                XXXXXX

                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXX XXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXX XXXX XXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX gettext(u'Create Account') 
                XXXXXXXXX
            XXXXXXX

            XXXX XXXXXXX XXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX gettext(u'OR') XXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX

            XXXX XXXXX XXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX gettext(u'Already have an account?') XXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Sign In') 
                XXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXXXXX
    XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXX X X X XXXXXX XXXXXXXX XXXX XXX XXXXXX
    X
    XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXX X XXX XXXX XXXXXXXX XXXX XXX XXXXXX
    X
    XXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXXXXXXXX
    X
XXXXXXXX
BBBBBBBB
