BBBB BBBBBB BBBB BBBBBBBBBBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXX

XXXXXX
    XXXX XXXXXX XXXXXXXXX XXXXX XXX
    XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX
        XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX XX XXX
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXX XXX XXXXXXXX
        XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXX

    XXXX XXXXXX XXXXXXX XXXXXXXX XXXX XXXXX XX XXXXXXXXX XXX
    XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXBBBBB BBBBB gettext(u'StatsFut | Football Analytics & Predictions') BBBBBBBBXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXBBBBB BBBBBBBBBBBBBBBB gettext(u"StatsFut - Advanced football statistics, pre-match analysis, Over/Under, BTTS and direct confrontations of the world's main leagues.") BBBBBBBBXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBBBBBBB BBBBX XX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBBBBBBB BBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBBBBBBB BBBBX XX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBBBBBBB BBBBX XX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBBBBBBB BBBBX XX
    XXXX XXXX XXXXX XXX XXXX XXX
    XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXBBBBB BBBBBBBB gettext(u'StatsFut | Football Analytics') BBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXBBBBB BBBBBBBBBBBBBB gettext(u'Advanced football statistics, predictions and analysis.') BBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXBBBBB BBBBBBBBXXXXXXXXXXXXXXXXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX

    XXXX XXXXX X XXXXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXX XXXX XXXXX XXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBXX
    XXXX XXXX XXXXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXXXXXX
        XX XXXXXXX X XXXXX XX XXXXXXX XX X XXXXXXX XXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXX XXXXXXXXXXX
            XXXXXXX X XXXXXXXXXXX
            XXXXXXX X XXXXXXXXXXX
            XXXXXXXX X XXXXXXXXXXX
        X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXX XXXXXXXXXXX
            XXXXXXX X XXXXXXXXXXX
            XXXXXXX X XXXXXXXXXXX
        X
    XXXXXXXX
XXXXXXX

XXXXXX
    XXXX XXXXXXX XXXXXXX XXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXX XXXXXXX XXXXXXXXXX XXX
    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXXX gettext(u'Main') XXXXXX
        XX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX
            XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Dashboard') 
        XXXX

        XXXX XXXX XXXX XXXX XXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
            XX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX  gettext(u'Live') 
        XXXX
        XXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXX gettext(u'Premium') XXXXXXX
            XXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
        XXXX

        XXXX XXXXXXXXXXXXXXXXXXX gettext(u'Countries & Leagues') XXXXXX
        
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXX
            BBB BBBBBBB BB BBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXX XXX XXXXXXXXXXXXX 
                    XXXXXXXXX
                XXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXX
                        BBB BBBBBB BB BBBBBBBBBBBBBBB
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        BBBBBB
                    XXXXXX
                XXXXXX
            XXXXXX
            BBBBB
            XXXX XXXXXXXX XX XX XXXXXXX XXXXX XX XX XXXXX XXXXXX XXXXXXXXXX XXX
            XXXX XXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXX gettext(u'Loading leagues...') XXXXXX
            BBBBBB
        XXXXXX
    XXXXXXXX

    XXXX XXXX XXXXXXX XXXX XXX
    XXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXX XXXXXX XXX XXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
            
            XXXX XXXXXX XXXX XXXXXX X XXXXX XXX
            XXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                XXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXXXX
                XXXX XXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXX
            XXXXXX

            XXXX XXXXXX XXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Search teams, leagues...') X XXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXX

            XXXX XXXX X XXXX X XXXXXXXX XXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXX XXXXXXXX XXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXX XXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXX
                XXXXXX

                XXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX BBB BB BB BB BBBB
                XXXXXX
                XXXX XXXX XXXX XXXXXX XXX
                BB BBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXX XXX XXXXXXX
                        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXX
                            FFFFFFFFFF
                        XXXXXX
                        XXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXBBBBB
                    XXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX  gettext(u'My Profile') XXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Premium') XXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX
                            XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBXX
                                BBBBBBBBBB
                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Sign Out') XXXXXXXXX
                            XXXXXXX
                        XXXXX
                    XXXXX
                XXXXXX
                BBBB
                XX XXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXX XXX XXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX gettext(u'Login') XXXXXXX
                XXXX
                BBBBB
            XXXXXX
        XXXXXXXXX

        XXXX XXXXXXX XXXXX XXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXX XXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXX XXXXX XXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXX XXXXXX XXX
        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
            XXXX XXXX XXXXXX XXXX XXXXX XXX
            XXXX XXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    BBBBB BBBBBB
                    XXX XXXXXXXXX XXXX XXXXXXXXXXXX gettext(u'Overview') XXXXX
                    BBBBBBBB
                XXXXXX
            XXXXXX
        XXXXXX

        BBBBB BBBBBBBBBBBBBBB

        XXXX XXXXXX XXX
        XXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXX XXXX XXXXX XXX
            XXXX XXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXX
                    XXXXXXXX gettext(u'Advanced Football Statistics & Predictions') XXXXXXXXX X 
                     gettext(u'StatsFut is the ultimate platform for football analysts, offering live score tracking, Both Teams to Score (BTTS) probabilities, Over/Under 2.5 goals trends, corner statistics, and detailed head-to-head (H2H) analysis. Find accurate football predictions today, algorithmic match analysis, and historical data for over 100 leagues worldwide (including Premier League, Brasileirão, La Liga, and Champions League). Boost your pre-match and in-play sports analysis with our data-driven edge.') 
                XXXXXX
            XXXXXX
            
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXX
                    XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
                        XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXX XXXXXXXXX  gettext(u'All rights reserved. Professional statistics for analysts.') XXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX
                        XXX XXXXXXXXXXXXXXXXX
                            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'About Us') XXXX
                        XXXXX
                        XXX XXXXXXXXXXXXXXXXX
                            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Privacy Policy') XXXX
                        XXXXX
                        XXX XXXXXXXXXXXXXXXXX
                            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Terms of Use') XXXX
                        XXXXX
                        XXX XXXXXXXXXXXXXXXXX
                            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Contact Us') XXXX
                        XXXXX
                    XXXXX
                XXXXXX
            XXXXXX
        XXXXXXXXX
    XXXXXXX

    XXXX XXXXXX XXXXXXX XXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXX XXXXXXX XXXXXXXXXX XXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX
                 gettext(u'We use cookies to personalize content and ads, provide social media features, and analyze our traffic. By continuing to use our site, you accept our use of cookies.') 
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Learn more') XXXX
            XXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Accept') XXXXXXXXX
        XXXXXX
    XXXXXX

    XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX
        XXX
    XXXXXXXXX

    XXXX XXXXXXXXX XXXXXX XXXX XXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX
        XX XXXXXXXXXX XXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XX XXXXXX XXXXXX XXXXX
        XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXX
        XXX XXXXXXXXXXX X XXX XX XXXXX XXXXXX XXXXXX XXXXXX

        XX XXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXX X XXX XX XXXXX XXXXXX XXXXX XX XXX XXXXX

                XX XXXXXXXXXXXXX X XX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXX X XXX
                    XXXXXXX
                X

                XXXXXXXXXXXXX X XXXXXXXXXXXXX XX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
                        XXXXXXXXXX XX X
                            XXXXXXXXXXXXXXXXXXXXXXX X XXX
                            XX XXXXXXXXXXXXXXXXXXXX X XX X
                                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XX X
                                    XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXXXXX X XXXXXXXXXXX
                                    XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXX XXXXXXXXXXXXXXXXXXXX
                                    XXXXXXXXXXXXXXXXXX X XXXXXX
                                    XXXXXXXXXXXXXX X X
                                        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXX
                                            XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
                                        XXXXXX
                                        XXXXX
                                            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                            XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                        XXXXXX
                                    XX
                                    XX XXX XXXXX XXXXXX XXX XX XX XXXX XXXX XXXXXXXX XXX
                                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
                                        XXXXXXXXXXX X XXXXXX
                                        XXXXXXXXXXXXXXXXXXX
                                    XXX
                                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXX
                            X XXXX X
                                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXX
                            X
                        XX
                        XXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX
                XX XXXXX
            XXX

            XX XXXXXX XXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
                XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXX XXX XX XXXXXXX

                XX XXXXXX XXX XXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXX X XXXXXXXXXXXX X XX X XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX
                X XXXX XX XXXXXX XXX XXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXX X XXXXXXXXXXXX X X X XXXXXXXXXXXXX X XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX
                X XXXX XX XXXXXX XXX XXXXXXXX X
                    XXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXX XX X XX XXXXXXXXXXXXXXXXXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    X
                X XXXX XX XXXXXX XXX XXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX
                X
            XXX

            XXXXXXXX XXXXXXXXXXXXXXXXXX X
                XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXX XXXXXX XX X
                    XX XXXXXX XXX XXXXXXXXXXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    X XXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    X
                XXX
            X

            XX XXXXX XXXXXX XXXX XXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                X
            XXX

            XX XXXXXXXX XXXXXXXX XXXXXXXXX X XX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
                XX XXXXXXXXXXX XX XXXXXXXXXX XX XXXXX XXX XXXX X
                    XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX
                X
            XXX
        X

        XX XXXXXX XXXXXXX XXXXXX XXXXX
        XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XX XXXXXXXXXXXXXX XX XXXXXXX XX XXXXXXXXXXXXXXX X
            XXXXXXXX XXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX X XXX
            X

            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        X
    XXXXXXXXX



    XXXX XXXXXX XX XXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXX XXXXXX XXX
    XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
        XXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXX XXX XX XXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX
            XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX
            XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

            XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX X XXXXXXX

            XXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXX X XXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX X XXXXXXXX
            XXXXXXXXXXXXXXXXXXX X XXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
            XX XXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
            X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX

            XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX

            XXX X
                XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX
            X XXXXXXXX XX
        XXX
    XXX
    XXXXXXXXX

    BBBBB BBBBBBBBBBBBBBBB
XXXXXXX

XXXXXXX
