# Mapeamento centralizado de nomes de times para evitar duplicatas
# Formato: "Nome Incorreto/Alternativo": "Nome Padronizado"

TEAM_NAME_MAPPINGS = {
    # Premier League
    "Manchester United FC": "Manchester Utd",
    "Manchester City FC": "Manchester City",
    "West Ham United FC": "West Ham Utd",
    "Newcastle United FC": "Newcastle Utd",
    "Tottenham Hotspur FC": "Tottenham",
    "Wolverhampton Wanderers FC": "Wolverhampton",
    "Leicester City FC": "Leicester",
    "Leeds United FC": "Leeds Utd",
    "Brighton & Hove Albion FC": "Brighton",
    "Arsenal FC": "Arsenal",
    "Chelsea FC": "Chelsea",
    "Liverpool FC": "Liverpool",
    "Everton FC": "Everton",
    "Fulham FC": "Fulham",
    "Brentford FC": "Brentford",
    "Crystal Palace FC": "Crystal Palace",
    "Southampton FC": "Southampton",
    "Aston Villa FC": "Aston Villa",
    "Sheffield United FC": "Sheffield United",
    "Burnley FC": "Burnley",
    "Luton Town FC": "Luton",
    "Norwich City FC": "Norwich",
    "Watford FC": "Watford",
    "Nottingham Forest FC": "Nottm Forest",
    "Ipswich Town FC": "Ipswich Town",
    "Wolves": "Wolverhampton",
    "Man City": "Manchester City",
    "Man United": "Manchester Utd",
    "Man Utd": "Manchester Utd",
    "Newcastle": "Newcastle Utd",
    "Nott'm Forest": "Nottm Forest",
    "Nottingham": "Nottm Forest",
    "Nottingham Forest": "Nottm Forest",
    "Nottingham Forest FC": "Nottm Forest",
    "West Ham": "West Ham Utd",
    "Leeds": "Leeds Utd",
    "Leeds United": "Leeds Utd",
    "Sunderland AFC": "Sunderland",
    "AFC Bournemouth": "Bournemouth",
    "Ipswich": "Ipswich Town",
    "Sheffield Utd": "Sheffield United",
    "Sheff Utd": "Sheffield United",
    "Bournemouth": "Bournemouth",
    "Luton": "Luton",

    # La Liga (Espanha)
    "Sociedad": "Sociedad",
    "Girona": "Girona",
    "Valencia": "Valencia",
    "Betis": "Betis",
    "Mallorca": "Mallorca",
    "Ath Bilbao": "Ath Bilbao",
    "Real Madrid": "Real Madrid",
    "Barcelona": "Barcelona",
    "Almeria": "Almeria",
    "Las Palmas": "Las Palmas",
    "Sevilla": "Sevilla",
    "Alaves": "Alaves",
    "Rayo Vallecano": "Rayo Vallecano",
    "Osasuna": "Osasuna",
    "Granada": "Granada",
    "Cadiz": "Cadiz",
    "Valladolid": "Valladolid",
    "Levante": "Levante",
    "Elche": "Elche",
    "Getafe": "Getafe",
    "Celta": "Celta",
    "Villarreal": "Villarreal",
    "Espanol": "Espanol",

    # Bundesliga (Alemanha)
    "Bayer 04 Leverkusen": "Leverkusen",
    "FC Bayern München": "Bayern Munich",
    "VfB Stuttgart": "Stuttgart",
    "RB Leipzig": "Leipzig",
    "Borussia Dortmund": "Dortmund",
    "Eintracht Frankfurt": "Frankfurt",
    "TSG 1899 Hoffenheim": "Hoffenheim",
    "1. FC Heidenheim 1846": "Heidenheim",
    "SV Werder Bremen": "Werder Bremen",
    "SC Freiburg": "Freiburg",
    "FC Augsburg": "Augsburg",
    "VfL Wolfsburg": "Wolfsburg",
    "1. FSV Mainz 05": "Mainz",
    "Borussia Mönchengladbach": "M Gladbach",
    "M'gladbach": "M Gladbach",
    "1. FC Union Berlin": "Union Berlin",
    "VfL Bochum 1848": "Bochum",
    "1. FC Köln": "Koln",
    "FC Koln": "Koln",
    "SV Darmstadt 98": "Darmstadt",
    "FC St. Pauli 1910": "St Pauli",
    "Holstein Kiel": "Holstein Kiel",
    "Hamburger SV": "Hamburg",
    "Hamburg SV": "Hamburg",
    "E. Frankfurt": "Frankfurt",
    "Ein Frankfurt": "Frankfurt",
    "Bayer Leverkusen": "Leverkusen",
    "FSV Mainz": "Mainz",
    "St. Pauli": "St Pauli",
    "FC St. Pauli": "St Pauli",
    "Bor. M'gladbach": "M Gladbach",
    "Borussia M'gladbach": "M Gladbach",
    "B. M'gladbach": "M Gladbach",
    "M'gladbach": "M Gladbach",
    "Hoffenheim": "Hoffenheim",
    "TSG Hoffenheim": "Hoffenheim",
    "VfL Wolfsburg": "Wolfsburg",
    "Wolfsburg": "Wolfsburg",

    # Pro League (Bélgica)
    "Union St.Gilloise": "Royale Union SG",
    "Union St.-Gilloise": "Royale Union SG",
    "Union Saint-Gilloise": "Royale Union SG",
    "St. Gilloise": "Royale Union SG",
    "St Gilloise": "Royale Union SG",
    "St. Truiden": "Sint-Truiden",
    "St Truiden": "Sint-Truiden",
    "Sint Truiden": "Sint-Truiden",
    "Waregem": "Zulte-Waregem",
    "Standard": "Standard Liege",
    "Standard Liège": "Standard Liege",
    "Standard de Liege": "Standard Liege",
    "Oud-Heverlee Leuven": "OH Leuven",
    "Oud Heverlee Leuven": "OH Leuven",
    "RAAL La Louviere": "La Louviere",
    "La Louvière": "La Louviere",
    "Cercle Brugge KSV": "Cercle Brugge",
    "KRC Genk": "Genk",
    "RSC Anderlecht": "Anderlecht",
    "KV Mechelen": "Mechelen",
    "Royal Antwerp FC": "Antwerp",
    "Sporting Charleroi": "Charleroi",

    # Brasileirão (e times sul-americanos que aparecem em competições)
    "SE Palmeiras": "Palmeiras",
    "CR Flamengo": "Flamengo",
    "Botafogo FR": "Botafogo",
    "São Paulo FC": "Sao Paulo",
    "Grêmio FBPA": "Gremio",
    "Clube Atlético Mineiro": "Atletico-MG",
    "Club Athletico Paranaense": "Athletico-PR",
    "Fluminense FC": "Fluminense",
    "Cuiabá EC": "Cuiaba",
    "SC Corinthians Paulista": "Corinthians",
    "Cruzeiro EC": "Cruzeiro",
    "SC Internacional": "Internacional",
    "Fortaleza EC": "Fortaleza",
    "EC Bahia": "Bahia",
    "CR Vasco da Gama": "Vasco",
    "EC Juventude": "Juventude",
    "AC Goianiense": "Atletico-GO",
    "Criciúma EC": "Criciuma",
    "EC Vitória": "Vitoria",
    "Red Bull Bragantino": "Bragantino",
    "Santos FC": "Santos",
    "Flamengo RJ": "Flamengo",
    "Botafogo RJ": "Botafogo",
    "CA Mineiro": "Atletico-MG",
    "Atletico Mineiro": "Atletico-MG",
    "CA Paranaense": "Athletico-PR",
    "Club Athletico Paranaense": "Athletico-PR",
    "Atletico Paranaense": "Athletico-PR",
    "Athletico": "Athletico-PR",
    "Coritiba FBC": "Coritiba",
    "Chapecoense AF": "Chapecoense",
    "Chapecoense-SC": "Chapecoense",
    "Clube do Remo": "Remo",
    "Mirassol FC": "Mirassol",
    "RB Bragantino": "Bragantino",
    "Red Bull Bragantino": "Bragantino",
    "Sao Paulo FC": "Sao Paulo",
    "Santos FC": "Santos",
    "Gremio FBPA": "Gremio",
    "Cruzeiro EC": "Cruzeiro",
    "EC Vitoria": "Vitoria",
    "Vasco da Gama": "Vasco",
    "Cuiaba Esporte Clube": "Cuiaba",
    "America FC": "America-MG", 
    "America MG": "America-MG",
    "Goias EC": "Goias",
    "Ceara SC": "Ceara",
    "Fortaleza EC": "Fortaleza",
    "EC Bahia": "Bahia",
    "Sport Club do Recife": "Sport Recife",
    "Avai FC": "Avai",
    "Juventude RS": "Juventude",
    "CSA": "CSA",
    "AC Goianiense": "Atletico-GO",
    "Atletico Goianiense": "Atletico-GO",
    "Criciuma EC": "Criciuma",
    "EC Juventude": "Juventude",
    "Fluminense FC": "Fluminense",
    "SC Corinthians Paulista": "Corinthians",
    "SE Palmeiras": "Palmeiras",
    "Juventude RS": "Juventude",
    "CSA": "CSA",
    "Atletico Goianiense": "Atletico-GO",
    "Sport Club do Recife": "Sport Recife",
    "Avai FC": "Avai",
    "Gremio Novorizontino": "Novorizontino",
    "Grêmio Novorizontino": "Novorizontino",
    "Clube De Regatas Brasil": "CRB",
    "Clube de Regatas Brasil": "CRB",
    "Nautico Recife": "Nautico",
    "America Mineiro": "America-MG",
    "Botafogo FC SP": "Botafogo-SP",
    "Operário Ferroviário": "Operario",
    "Operario-PR": "Operario",
    "Amazonas FC": "Amazonas",
    "Paysandu SC": "Paysandu",
    "Brusque FC": "Brusque",
    "São Bernardo FC": "Sao Bernardo",
    "Volta Redonda FC": "Volta Redonda",
    "Ferroviária": "Ferroviaria",
    "Ypiranga FC": "Ypiranga",
    "Londrina EC": "Londrina",
    
    # Dinamarca
    "AGF": "Aarhus",
    "AGF Aarhus": "Aarhus",
    "AaB": "Aalborg",
    "AaB Aalborg": "Aalborg",
    "OB": "Odense",
    "OB Odense": "Odense",
    "FC Kobenhavn": "FC Copenhagen",
    "Kobenhavn": "FC Copenhagen",
    "Brondby IF": "Brondby",
    "Randers": "Randers FC",
    "Silkeborg IF": "Silkeborg",
    "SonderjyskE": "Sonderjyske",
    "Viborg FF": "Viborg",
    "Vejle BK": "Vejle",
    "Lyngby BK": "Lyngby",
    "AC Horsens": "Horsens",
    "Hobro IK": "Hobro",
    "FC Helsingor": "Helsingor",

    # Argentina (Adicionar conforme necessário)
    # "River Plate ...": "River Plate",

    # La Liga (Espanha)
    "RCD Espanyol de Barcelona": "Espanol",
    "RC Celta de Vigo": "Celta",
    "Villarreal CF": "Villarreal",
    "Getafe CF": "Getafe",
    "Sevilla FC": "Sevilla",
    "Deportivo Alavés": "Alaves",
    "Real Sociedad de Fútbol": "Sociedad",

    # Áustria (Bundesliga) - Padronização SoccerStats
    "RB Salzburg": "Salzburg",
    "Red Bull Salzburg": "Salzburg",
    "FC Red Bull Salzburg": "Salzburg",
    "SK Rapid": "Rapid Wien",
    "Rapid Vienna": "Rapid Wien",
    "SK Rapid Wien": "Rapid Wien",
    "Blau-Weiss Linz": "BW Linz",
    "FC Blau-Weiß Linz": "BW Linz",
    "Blau Weiss Linz": "BW Linz",
    "LASK": "LASK Linz",
    "LASK Linz": "LASK Linz",  # Ensure idempotent
    "Austria Vienna": "Austria Wien",
    "FK Austria Wien": "Austria Wien",
    "WSG Tirol": "Tirol",
    "TSV Hartberg": "Hartberg",
    "SCR Altach": "Altach",
    "Rheindorf Altach": "Altach",
    "SV Ried": "Ried",
    "Grazer AK 1902": "Grazer AK",
    "GAK": "Grazer AK",
    "Wolfsberg": "Wolfsberger AC",
    "Club Atlético de Madrid": "Ath Madrid",
    "Athletic Club": "Ath Bilbao",
    "Real Betis Balompié": "Betis",
    "RCD Mallorca": "Mallorca",
    "Valencia CF": "Valencia",
    "Girona FC": "Girona",
    "Real Madrid CF": "Real Madrid",
    "Levante UD": "Levante",
    "Elche CF": "Elche",
    "Cádiz CF": "Cadiz",
    "Real Valladolid CF": "Valladolid",
    "CA Osasuna": "Osasuna",
    "Rayo Vallecano de Madrid": "Rayo Vallecano",
    "Vallecano": "Rayo Vallecano",
    "UD Las Palmas": "Las Palmas",
    "Granada CF": "Granada",
    "UD Almería": "Almeria",
    "FC Barcelona": "Barcelona",
    "Oviedo": "Real Oviedo",
    "PSG": "PSG",
    'Saint-Etienne': 'St Etienne',
    'Saint-Étienne': 'St Etienne',
    'AS Saint-Étienne': 'St Etienne',
    'St Etienne': 'St Etienne',
    'RC Strasbourg Alsace': 'Strasbourg',
    'RC Strasbourg': 'Strasbourg',
    'Strasbourg': 'Strasbourg',
    'Paris SG': 'PSG',
    'Paris Saint-Germain': 'PSG',
    'OGC Nice': 'Nice',
    'Nice': 'Nice',
    'Lyon': 'Lyon',
    'Olympique Lyonnais': 'Lyon',
    'Marseille': 'Marseille',
    'Olympique de Marseille': 'Marseille',
    'Lille': 'Lille',
    'Lille OSC': 'Lille',
    'Monaco': 'Monaco',
    'AS Monaco': 'Monaco',
    'Lens': 'Lens',
    'RC Lens': 'Lens',
    'Brest': 'Brest',
    'Stade Brestois': 'Brest',
    'Rennes': 'Rennes',
    'Stade Rennais': 'Rennes',
    'Toulouse': 'Toulouse',
    'Toulouse FC': 'Toulouse',
    'Nantes': 'Nantes',
    'FC Nantes': 'Nantes',
    'Reims': 'Reims',
    'Stade de Reims': 'Reims',
    'Montpellier': 'Montpellier',
    'Montpellier HSC': 'Montpellier',
    'Lorient': 'Lorient',
    'FC Lorient': 'Lorient',
    'Angers': 'Angers',
    'Angers SCO': 'Angers',
    'Auxerre': 'Auxerre',
    'AJ Auxerre': 'Auxerre',
    'Le Havre': 'Le Havre',
    'Le Havre AC': 'Le Havre',
    'Paris FC': 'Paris FC',
    'Metz': 'Metz',
    'FC Metz': 'Metz',
    'Clermont': 'Clermont',
    'Clermont Foot 63': 'Clermont',

    # Serie A (Italia)
    "FC Internazionale Milano": "Inter",
    "AC Milan": "Milan",
    "Juventus FC": "Juventus",
    "Bologna FC 1909": "Bologna",
    "AS Roma": "Roma",
    "Atalanta BC": "Atalanta",
    "SS Lazio": "Lazio",
    "ACF Fiorentina": "Fiorentina",
    "Torino FC": "Torino",
    "SSC Napoli": "Napoli",
    "Genoa CFC": "Genoa",
    "AC Monza": "Monza",
    "Hellas Verona FC": "Verona",
    "US Lecce": "Lecce",
    "Udinese Calcio": "Udinese",
    "Cagliari Calcio": "Cagliari",
    "Empoli FC": "Empoli",
    "Frosinone Calcio": "Frosinone",
    "US Sassuolo Calcio": "Sassuolo",
    "US Salernitana 1919": "Salernitana",
    "Parma Calcio 1913": "Parma",
    "Como 1907": "Como",
    "Venezia FC": "Venezia",

    # Australia (A-League)
    "Adelaide Utd": "Adelaide United",
    "WS Wanderers": "Western Sydney Wanderers",
    "Melbourne V.": "Melbourne Victory",
    "Auckland": "Auckland FC",
    "Wellington": "Wellington Phoenix FC",
    "Central Coast": "Central Coast Mariners",
    "Newcastle Jets": "Newcastle Jets FC",
    "Macarthur": "Macarthur FC",
    "Sydney": "Sydney FC",
    "Brisbane": "Brisbane Roar",
    "Melbourne C.": "Melbourne City",
    "Western Utd": "Western United",
    "Western United FC": "Western United",
}

COUNTRY_TRANSLATIONS = {
    "Inglaterra": "England",
    "Espanha": "Spain",
    "Alemanha": "Germany",
    "Italia": "Italy",
    "Franca": "France",
    "Holanda": "Netherlands",
    "Belgica": "Belgium",
    "Portugal": "Portugal",
    "Turquia": "Turkey",
    "Grecia": "Greece",
    "Austria": "Austria",
    "Brasil": "Brazil",
    "Argentina": "Argentina",
    "Australia": "Australia",
    "Suica": "Switzerland",
    "Chile": "Chile",
    "Republica Tcheca": "Czech Republic",
    "Dinamarca": "Denmark",
    "Finlandia": "Finland",
    "Noruega": "Norway",
    "Suecia": "Sweden",
    "Polonia": "Poland",
    "Ucrania": "Ukraine",
    "Russia": "Russia",
    "Japao": "Japan",
    "Coreia do Sul": "South Korea",
    "Escocia": "Scotland",
    "Mexico": "Mexico",
    "Estados Unidos": "USA",
    "Irlanda": "Ireland",
    "Gales": "Wales",
    "Uruguai": "Uruguay",
    "Paraguai": "Paraguay",
    "Islandia": "Iceland",
    "Equador": "Ecuador",
    "Peru": "Peru",
    "America do Sul": "South America",
}

COUNTRY_REVERSE_TRANSLATIONS = {v.lower(): k for k, v in COUNTRY_TRANSLATIONS.items()}

import unicodedata

def normalize_team_name(name):
    """
    Retorna o nome padronizado do time, se existir no mapeamento.
    Remove caracteres especiais e acentos do nome original se não houver mapeamento.
    """
    if not name:
        return None
    
    clean_name = name.strip()
    
    # Busca case-insensitive no mapeamento
    clean_name_lower = clean_name.lower()
    for k, v in TEAM_NAME_MAPPINGS.items():
        if k.lower() == clean_name_lower:
            return v
        
    # Substituições manuais para caracteres nórdicos/especiais que o NFKD não remove
    replacements = {
        'ø': 'o', 'Ø': 'O',
        'æ': 'ae', 'Æ': 'Ae',
        'ð': 'd', 'Ð': 'D',
        'þ': 'th', 'Þ': 'Th',
        'ß': 'ss'
    }
    for char, replacement in replacements.items():
        clean_name = clean_name.replace(char, replacement)
        
    # Remove acentos (ex: Örebro -> Orebro, São Paulo -> Sao Paulo)
    nfkd_form = unicodedata.normalize('NFKD', clean_name)
    clean_name_no_accents = "".join([c for c in nfkd_form if not unicodedata.combining(c)])
    
    return clean_name_no_accents

def get_flag_code(country_name):
    """
    Helper to map country names to Flag Icons (fi fi-xx).
    """
    country_lower = country_name.lower()
    
    # Map common names to ISO codes or 'fi' codes
    mapping = {
        'england': 'gb-eng',
        'uk': 'gb',
        'united kingdom': 'gb',
        'spain': 'es',
        'brazil': 'br',
        'brasil': 'br',
        'italy': 'it',
        'germany': 'de',
        'france': 'fr',
        'portugal': 'pt',
        'netherlands': 'nl',
        'holland': 'nl',
        'belgium': 'be',
        'argentina': 'ar',
        'usa': 'us',
        'united states': 'us',
        'turkey': 'tr',
        'russia': 'ru',
        'ukraine': 'ua',
        'sweden': 'se',
        'norway': 'no',
        'denmark': 'dk',
        'finland': 'fi',
        'austria': 'at',
        'switzerland': 'ch',
        'czech republic': 'cz',
        'czechia': 'cz',
        'poland': 'pl',
        'greece': 'gr',
        'scotland': 'gb-sct',
        'wales': 'gb-wls',
        'ireland': 'ie',
        'colombia': 'co',
        'chile': 'cl',
        'mexico': 'mx',
        'uruguay': 'uy',
        'japan': 'jp',
        'south korea': 'kr',
        'china': 'cn',
        'australia': 'au',
        # Add Portuguese names just in case
        'inglaterra': 'gb-eng',
        'espanha': 'es',
        'italia': 'it',
        'itália': 'it',
        'alemanha': 'de',
        'franca': 'fr',
        'frança': 'fr',
        'holanda': 'nl',
        'belgica': 'be',
        'bélgica': 'be',
        'estados unidos': 'us',
        'turquia': 'tr',
        'russia': 'ru',
        'rússia': 'ru',
        'ucrania': 'ua',
        'ucrânia': 'ua',
        'suecia': 'se',
        'suécia': 'se',
        'noruega': 'no',
        'dinamarca': 'dk',
        'finlandia': 'fi',
        'finlândia': 'fi',
        'grecia': 'gr',
        'grécia': 'gr',
        'japao': 'jp',
        'japão': 'jp',
        'polonia': 'pl',
        'polônia': 'pl',
        'austrália': 'au',
        'áustria': 'at',
        'suica': 'ch',
        'suíça': 'ch',
        'republica tcheca': 'cz',
        'república tcheca': 'cz',
        'coreia do sul': 'kr',
        'escocia': 'gb-sct',
        'escócia': 'gb-sct',
        'méxico': 'mx',
        'irlanda': 'ie',
        'gales': 'gb-wls',
        'uruguai': 'uy',
        'paraguai': 'py',
        'paraguay': 'py',
        'islandia': 'is',
        'iceland': 'is',
        'equador': 'ec',
        'ecuador': 'ec',
        'peru': 'pe',
        'america do sul': 'un',
        'south america': 'un',
    }
    
    return mapping.get(country_lower, 'xx') # 'xx' as generic/unknown
