# Mapeamento centralizado de nomes de times para evitar duplicatas
# Formato: "Nome Incorreto/Alternativo": "Nome Padronizado"

TEAM_NAME_MAPPINGS = {
    # Premier League
    "Manchester United FC": "Manchester Utd",
    "Manchester City FC": "Manchester City",
    "West Ham United FC": "West Ham Utd",
    "Newcastle United FC": "Newcastle Utd",
    "Tottenham Hotspur FC": "Tottenham",
    "Wolverhampton Wanderers FC": "Wolverhampton",
    "Leicester City FC": "Leicester",
    "Leeds United FC": "Leeds Utd",
    "Brighton & Hove Albion FC": "Brighton",
    "Arsenal FC": "Arsenal",
    "Chelsea FC": "Chelsea",
    "Liverpool FC": "Liverpool",
    "Everton FC": "Everton",
    "Fulham FC": "Fulham",
    "Brentford FC": "Brentford",
    "Crystal Palace FC": "Crystal Palace",
    "Southampton FC": "Southampton",
    "Aston Villa FC": "Aston Villa",
    "Sheffield United FC": "Sheffield United",
    "Burnley FC": "Burnley",
    "Luton Town FC": "Luton",
    "Norwich City FC": "Norwich",
    "Watford FC": "Watford",
    "Nottingham Forest FC": "Nottm Forest",
    "Ipswich Town FC": "Ipswich Town",
    "Wolves": "Wolverhampton",
    "Man City": "Manchester City",
    "Man United": "Manchester Utd",
    "Man Utd": "Manchester Utd",
    "Newcastle": "Newcastle Utd",
    "Nott'm Forest": "Nottm Forest",
    "Nottingham": "Nottm Forest",
    "Nottingham Forest": "Nottm Forest",
    "Nottingham Forest FC": "Nottm Forest",
    "West Ham": "West Ham Utd",
    "Leeds": "Leeds Utd",
    "Leeds United": "Leeds Utd",
    "Sunderland AFC": "Sunderland",
    "AFC Bournemouth": "Bournemouth",
    "Ipswich": "Ipswich Town",
    "Sheffield Utd": "Sheffield United",
    "Sheff Utd": "Sheffield United",

    # Bundesliga (Alemanha)
    "Bayer 04 Leverkusen": "Leverkusen",
    "FC Bayern München": "Bayern Munich",
    "VfB Stuttgart": "Stuttgart",
    "RB Leipzig": "Leipzig",
    "Borussia Dortmund": "Dortmund",
    "Eintracht Frankfurt": "Frankfurt",
    "TSG 1899 Hoffenheim": "Hoffenheim",
    "1. FC Heidenheim 1846": "Heidenheim",
    "SV Werder Bremen": "Werder Bremen",
    "SC Freiburg": "Freiburg",
    "FC Augsburg": "Augsburg",
    "VfL Wolfsburg": "Wolfsburg",
    "1. FSV Mainz 05": "Mainz",
    "Borussia Mönchengladbach": "M Gladbach",
    "M'gladbach": "M Gladbach",
    "1. FC Union Berlin": "Union Berlin",
    "VfL Bochum 1848": "Bochum",
    "1. FC Köln": "Koln",
    "FC Koln": "Koln",
    "SV Darmstadt 98": "Darmstadt",
    "FC St. Pauli 1910": "St Pauli",
    "Holstein Kiel": "Holstein Kiel",
    "Hamburger SV": "Hamburg",
    "Hamburg SV": "Hamburg",
    "E. Frankfurt": "Frankfurt",
    "Ein Frankfurt": "Frankfurt",
    "Bayer Leverkusen": "Leverkusen",
    "FSV Mainz": "Mainz",

    # Pro League (Bélgica)
    "Union St.Gilloise": "Royale Union SG",
    "Union St.-Gilloise": "Royale Union SG",
    "Union Saint-Gilloise": "Royale Union SG",
    "St. Gilloise": "Royale Union SG",
    "St Gilloise": "Royale Union SG",
    "St. Truiden": "Sint-Truiden",
    "St Truiden": "Sint-Truiden",
    "Sint Truiden": "Sint-Truiden",
    "Waregem": "Zulte-Waregem",
    "Standard": "Standard Liege",
    "Standard Liège": "Standard Liege",
    "Standard de Liege": "Standard Liege",
    "Oud-Heverlee Leuven": "OH Leuven",
    "Oud Heverlee Leuven": "OH Leuven",
    "RAAL La Louviere": "La Louviere",
    "La Louvière": "La Louviere",
    "Cercle Brugge KSV": "Cercle Brugge",
    "KRC Genk": "Genk",
    "RSC Anderlecht": "Anderlecht",
    "KV Mechelen": "Mechelen",
    "Royal Antwerp FC": "Antwerp",
    "Sporting Charleroi": "Charleroi",

    # Brasileirão (e times sul-americanos que aparecem em competições)
    "SE Palmeiras": "Palmeiras",
    "CR Flamengo": "Flamengo",
    "Botafogo FR": "Botafogo",
    "São Paulo FC": "Sao Paulo",
    "Grêmio FBPA": "Gremio",
    "Clube Atlético Mineiro": "Atletico-MG",
    "Club Athletico Paranaense": "Athletico-PR",
    "Fluminense FC": "Fluminense",
    "Cuiabá EC": "Cuiaba",
    "SC Corinthians Paulista": "Corinthians",
    "Cruzeiro EC": "Cruzeiro",
    "SC Internacional": "Internacional",
    "Fortaleza EC": "Fortaleza",
    "EC Bahia": "Bahia",
    "CR Vasco da Gama": "Vasco",
    "EC Juventude": "Juventude",
    "AC Goianiense": "Atletico-GO",
    "Criciúma EC": "Criciuma",
    "EC Vitória": "Vitoria",
    "Red Bull Bragantino": "Bragantino",
    "Santos FC": "Santos",
    "Flamengo RJ": "Flamengo",
    "Botafogo RJ": "Botafogo",
    "CA Mineiro": "Atletico-MG",
    "Atletico Mineiro": "Atletico-MG",
    "CA Paranaense": "Athletico-PR",
    "Club Athletico Paranaense": "Athletico-PR",
    "Coritiba FBC": "Coritiba",
    "Chapecoense AF": "Chapecoense",
    "Chapecoense-SC": "Chapecoense",
    "Clube do Remo": "Remo",
    "Mirassol FC": "Mirassol",
    "RB Bragantino": "Bragantino",
    "Red Bull Bragantino": "Bragantino",
    "Sao Paulo FC": "Sao Paulo",
    "Santos FC": "Santos",
    "Gremio FBPA": "Gremio",
    "Cruzeiro EC": "Cruzeiro",
    "EC Vitoria": "Vitoria",
    "Vasco da Gama": "Vasco",
    "Cuiaba Esporte Clube": "Cuiaba",
    "America FC": "America-MG", 
    "America MG": "America-MG",
    "Goias EC": "Goias",
    "Ceara SC": "Ceara",
    "Fortaleza EC": "Fortaleza",
    "EC Bahia": "Bahia",
    "Sport Club do Recife": "Sport Recife",
    "Avai FC": "Avai",
    "Juventude RS": "Juventude",
    "CSA": "CSA",
    "AC Goianiense": "Atletico-GO",
    "Atletico Goianiense": "Atletico-GO",
    "Criciuma EC": "Criciuma",
    "EC Juventude": "Juventude",
    "Fluminense FC": "Fluminense",
    "Botafogo FR": "Botafogo",
    "CR Vasco da Gama": "Vasco",
    "SC Corinthians Paulista": "Corinthians",
    "SE Palmeiras": "Palmeiras",
    "Juventude RS": "Juventude",
    "CSA": "CSA",
    "Atletico Goianiense": "Atletico-GO",
    "Sport Club do Recife": "Sport Recife",
    "Avai FC": "Avai",
    
    # Dinamarca
    "AGF": "Aarhus",
    "AGF Aarhus": "Aarhus",
    "AaB": "Aalborg",
    "AaB Aalborg": "Aalborg",
    "OB": "Odense",
    "OB Odense": "Odense",
    "FC Kobenhavn": "FC Copenhagen",
    "Kobenhavn": "FC Copenhagen",
    "Brondby IF": "Brondby",
    "Randers": "Randers FC",
    "Silkeborg IF": "Silkeborg",
    "SonderjyskE": "Sonderjyske",
    "Viborg FF": "Viborg",
    "Vejle BK": "Vejle",
    "Lyngby BK": "Lyngby",
    "AC Horsens": "Horsens",
    "Hobro IK": "Hobro",
    "FC Helsingor": "Helsingor",

    # Argentina (Adicionar conforme necessário)
    # "River Plate ...": "River Plate",

    # La Liga (Espanha)
    "RCD Espanyol de Barcelona": "Espanol",
    "RC Celta de Vigo": "Celta",
    "Villarreal CF": "Villarreal",
    "Getafe CF": "Getafe",
    "Sevilla FC": "Sevilla",
    "Deportivo Alavés": "Alaves",
    "Real Sociedad de Fútbol": "Sociedad",

    # Áustria (Bundesliga) - Padronização SoccerStats
    "RB Salzburg": "Salzburg",
    "Red Bull Salzburg": "Salzburg",
    "FC Red Bull Salzburg": "Salzburg",
    "SK Rapid": "Rapid Wien",
    "Rapid Vienna": "Rapid Wien",
    "SK Rapid Wien": "Rapid Wien",
    "Blau-Weiss Linz": "BW Linz",
    "FC Blau-Weiß Linz": "BW Linz",
    "Blau Weiss Linz": "BW Linz",
    "LASK": "LASK Linz",
    "LASK Linz": "LASK Linz",  # Ensure idempotent
    "Austria Vienna": "Austria Wien",
    "FK Austria Wien": "Austria Wien",
    "WSG Tirol": "Tirol",
    "TSV Hartberg": "Hartberg",
    "SCR Altach": "Altach",
    "Rheindorf Altach": "Altach",
    "SV Ried": "Ried",
    "Grazer AK 1902": "Grazer AK",
    "GAK": "Grazer AK",
    "Wolfsberg": "Wolfsberger AC",
    "Club Atlético de Madrid": "Ath Madrid",
    "Athletic Club": "Ath Bilbao",
    "Real Betis Balompié": "Betis",
    "RCD Mallorca": "Mallorca",
    "Valencia CF": "Valencia",
    "Girona FC": "Girona",
    "Real Madrid CF": "Real Madrid",
    "Levante UD": "Levante",
    "Elche CF": "Elche",
    "Cádiz CF": "Cadiz",
    "Real Valladolid CF": "Valladolid",
    "CA Osasuna": "Osasuna",
    "Rayo Vallecano de Madrid": "Rayo Vallecano",
    "Vallecano": "Rayo Vallecano",
    "UD Las Palmas": "Las Palmas",
    "Granada CF": "Granada",
    "UD Almería": "Almeria",
    "FC Barcelona": "Barcelona",
    "Oviedo": "Real Oviedo",
    "R. Oviedo": "Real Oviedo",

    # Serie A (Italia)
    "FC Internazionale Milano": "Inter",
    "AC Milan": "Milan",
    "Juventus FC": "Juventus",
    "Bologna FC 1909": "Bologna",
    "AS Roma": "Roma",
    "Atalanta BC": "Atalanta",
    "SS Lazio": "Lazio",
    "ACF Fiorentina": "Fiorentina",
    "Torino FC": "Torino",
    "SSC Napoli": "Napoli",
    "Genoa CFC": "Genoa",
    "AC Monza": "Monza",
    "Hellas Verona FC": "Verona",
    "US Lecce": "Lecce",
    "Udinese Calcio": "Udinese",
    "Cagliari Calcio": "Cagliari",
    "Empoli FC": "Empoli",
    "Frosinone Calcio": "Frosinone",
    "US Sassuolo Calcio": "Sassuolo",
    "US Salernitana 1919": "Salernitana",
    "Parma Calcio 1913": "Parma",
    "Como 1907": "Como",
    "Venezia FC": "Venezia",

    # Ligue 1 (Franca)
    "Paris Saint-Germain FC": "PSG",
    "AS Monaco FC": "Monaco",
    "Stade Brestois 29": "Brest",
    "Lille OSC": "Lille",
    "OGC Nice": "Nice",
    "Olympique Lyonnais": "Lyon",
    "Racing Club de Lens": "Lens",
    "Olympique de Marseille": "Marseille",
    "Stade de Reims": "Reims",
    "Stade Rennais FC 1901": "Rennes",
    "Toulouse FC": "Toulouse",
    "Montpellier HSC": "Montpellier",
    "RC Strasbourg Alsace": "Strasbourg",
    "FC Nantes": "Nantes",
    "Le Havre AC": "Le Havre",
    "FC Metz": "Metz",
    "FC Lorient": "Lorient",
    "Clermont Foot 63": "Clermont",
    "AS Saint-Étienne": "St Etienne",
    "AJ Auxerre": "Auxerre",
    "Angers SCO": "Angers",
    
    # Australia (A-League)
    "Adelaide Utd": "Adelaide United",
    "WS Wanderers": "Western Sydney Wanderers",
    "Melbourne V.": "Melbourne Victory",
    "Auckland": "Auckland FC",
    "Wellington": "Wellington Phoenix FC",
    "Central Coast": "Central Coast Mariners",
    "Newcastle Jets": "Newcastle Jets FC",
    "Macarthur": "Macarthur FC",
    "Sydney": "Sydney FC",
    "Brisbane": "Brisbane Roar",
    "Melbourne C.": "Melbourne City",
    "Western Utd": "Western United",
    "Western United FC": "Western United",
}

COUNTRY_TRANSLATIONS = {
    "Inglaterra": "England",
    "Espanha": "Spain",
    "Alemanha": "Germany",
    "Italia": "Italy",
    "Franca": "France",
    "Holanda": "Netherlands",
    "Belgica": "Belgium",
    "Portugal": "Portugal",
    "Turquia": "Turkey",
    "Grecia": "Greece",
    "Austria": "Austria",
    "Brasil": "Brazil",
    "Argentina": "Argentina",
    "Australia": "Australia",
    "Suica": "Switzerland",
    "Republica Tcheca": "Czech Republic",
    "Dinamarca": "Denmark",
    "Finlandia": "Finland",
    "Noruega": "Norway",
    "Suecia": "Sweden",
    "Polonia": "Poland",
    "Ucrania": "Ukraine",
    "Russia": "Russia",
    "Japao": "Japan",
}

COUNTRY_REVERSE_TRANSLATIONS = {v.lower(): k for k, v in COUNTRY_TRANSLATIONS.items()}

def normalize_team_name(name):
    """
    Retorna o nome padronizado do time, se existir no mapeamento.
    Caso contrário, retorna o nome original limpo.
    """
    if not name:
        return None
    
    clean_name = name.strip()
    
    # Tenta busca exata (com strip)
    result = TEAM_NAME_MAPPINGS.get(clean_name)
    if result:
        return result
        
    # Tenta busca case-insensitive se necessário (opcional, mas seguro)
    # Por enquanto o strip já resolve 99% dos casos do CSV.
    return clean_name
