# Generated by Django 5.0.1 on 2026-06-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plan_type',
            field=models.CharField(choices=[('popular', 'Popular'), ('vip', 'VIP')], default='popular', help_text='Tipo de plano premium do usuário', max_length=10),
        ),
    ]
